### ISSUE TITLE
 TASK 165   2. setEasyTimeout transform the `time` object into `ms` and pass correct value as a second argument of setTimeout

### ISSUE THREAD

**Issue by w0rstR** [AgileNix/coderslang-feedback#10]
![rrrr](https://user-images.githubusercontent.com/64990075/99899985-e190d480-2cb5-11eb-939d-aa3ff1e581b9.JPG)
The function works correctly
I do not understand what is wrong

**Comment by ssfxate** [comment]
Check for the formula in setTimeout. You are close to the correct solution, but still have mistakes.
First of all, how many seconds in hour?…

And check for the second check in the bottom right corner on your screenshot. There is the second hint.

**Comment by AgileNix** [comment]
- you don't need to declare an additional time constant.
- `time=` assignment is unnecessary
- the multiples are incorrect and should be fixed, i.e. hours should be multiplied by 1000 * 60 * 60
