### ISSUE TITLE
TASK 2174 (russian version)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#100]
Исправь позиционирование

Твой коллега добавил для **бвух** блоков **нумерация**. //  двух, нумерация

Номера должны **появиятся** в нижнем правом углу каждого блока. // появляться

Но они там не появляются, нужно внести правки.

Задай нужное значения для свойств position, right и bottom для элементов с классом block-number.

**Comment by amatiyko** [comment]
@ssfxate done. thank you.
Please, delete the task2174 folder and then download tasks again to see changes.
