### ISSUE TITLE
[TASK] [NUMBER] 160

### ISSUE THREAD

**Issue by lamixane** [AgileNix/coderslang-feedback#103]
## Test result 

  - [ ] {
  "en": "`delayedLog` should call `setTimeout` once",
  "ru": "`delayedLog` должна вызывать `setTimeout` один раз"
}
        
  - [ ] {
  "en": "The second parameter of `setTimeout` should be `n * 1000`",
  "ru": "Второй параметр `setTimeout` должен быть `n * 1000`"
}
        
  - [x] {
  "en": "String `s` should be passed into `console.log` without any modifications",
  "ru": "Строку `s` нужно передать в `console.log` без каких-либо изменений"
}
        
#### task160/functions.js
  ```js
  export const delayedLog = (s, n) =>{
 
  console.log(s);
}
  ```
        
  #### task160/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task160/solution.js
  ```js
  /**
 * Implement the function delayedLog(s, n)
 *
 * It should print the string `s` to the console after `n` seconds.
 *
 * */

import { delayedLog } from './functions.js';

setTimeout(() => {delayedLog('1 second..',1)
},1 * 1000);
setTimeout(() => {delayedLog('2 second..',2)
},2 * 1000);
setTimeout(() => {delayedLog('4 second..',4)
},4 * 1000);
setTimeout(() => {delayedLog('8 second..',8)
},8 * 1000);
  ```
        

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ ] Yes

**Comment by lamixane** [comment]
output is correct but two submission requirement are crossed off

**Comment by AgileNix** [comment]
@lamixane the `setTimeout` should be inside the `delayedLog`.

Btw, that's exactly what the hint suggests:
```bash
delayedLog should call setTimeout once
```

**Comment by AgileNix** [comment]
@lamixane have you solved this task and we can close the issue?
