### ISSUE TITLE
task 130

### ISSUE THREAD

**Issue by quantumbaze33** [AgileNix/coderslang-feedback#104]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ ] Yes

### What solutions have you tried to solve the task?
![Challenge_Comprehension](https://user-images.githubusercontent.com/80545345/111063405-8fff9600-84ae-11eb-82a7-b0417473e192.PNG)
### Your code

let i = 0;

while (i < 99) {
  console.log(i.toString());
  i++;
}

export const myLoop = () => {
  console.log(i.toString());
};

**Comment by AgileNix** [comment]
Please show your code.

Based on the errors that you've posted, the issue is far from String vs Number. You need to make sure that the while loop is inside the function `myLoop`.

**Comment by quantumbaze33** [comment]
Ok... So it is not an issue of String vs Number.. Let me retrace back..

**Comment by quantumbaze33** [comment]
I am getting the expected output (0 - 99)

import { myLoop } from './helper.js';

let i = 0;

while (i < myLoop.length) {
    console.log(i);
    i++
}

Since the last iteration stops at 98 for myLoop.length, I edited the helper.js:

let i = 0;

while (i < 100) {
  console.log(i);
  i++;
}

export const myLoop = () => {
  console.log(i);
};

I hope I am not complicating it.. And from your last comment, I don't understand this statement "make sure the while loop is inside the function myLoop). Does the statement correspond to the first code in this comment.

**Comment by quantumbaze33** [comment]
At last... I solved it! Thank you...
