### ISSUE TITLE
Task92

### ISSUE THREAD

**Issue by Skippik** [AgileNix/coderslang-feedback#107]
#### task92/helper.js
  ```js
  
const readlineSync = require('readline-sync');

export const askNameAndGreet = () => {
  const name = readlineSync.question('Please enter your name: ');
  console.log(`Hello, ${name}!`);
}



  ```
        
  #### task92/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task92/solution.js
  ```js
  /**
 * The code is broken.
 *
 * You need to install the module readline sync and import it
 *
 * Only one import string should be added to helper.js.
 *
 * Don't change solution.js.
 * */

import { askNameAndGreet } from './helper.js'

askNameAndGreet();
  ```

**Comment by ssfxate** [comment]
Hey. What are you asking about?
Your code is looking good. What error do you have?

Have you installed the module readline-sync via npm into the folder of the task?

**Comment by Skippik** [comment]
модуль установлен. Но импорт не могу понять как сделать, в документации var readlineSync = require('readline-sync'); но при импорте выдаёт ошибку(

**Comment by Skippik** [comment]
export const askNameAndGreet = () => {
  var readlineSync = require('readline-sync');
  const name = readlineSync.question('Please enter your name: ');
  console.log(`Hello, ${name}!`);
}

код с helper.js

**Comment by ssfxate** [comment]
https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/#es6-modules

**Comment by AgileNix** [comment]
@Skippik have you solved the task and we can close the issue?
