### ISSUE TITLE
Task 102 keeps saying sayHello should return the proper greeting 

### ISSUE THREAD

**Issue by emmaxy07** [AgileNix/coderslang-feedback#109]
export const sayHello = (name) => {
  return('Hello,' + name + '!');
}

import { sayHello } from './helper.js';

console.log(sayHello('John'));   // Hello, John!
console.log(sayHello('Sandy'));  // Hello, Sandy!

**Comment by AgileNix** [comment]
@emmaxy07 looks like the space character is missing after the comma.
Should be like this:
```js
return 'Hello, ' + name + '!';
```
