### ISSUE TITLE
TASK 146

### ISSUE THREAD

**Issue by w0rstR** [AgileNix/coderslang-feedback#11]
1. checkSpam should return a boolean(good)

2. checkSpam should return true if the match is found

3. checkSpam should return true if no match is found(good)

4. checkSpam should make case insensitive match

```

export const checkSpam = (text, spamKeywords) => {
  
  if(text.includes(spamKeywords)){
    return true
  }else{
    return false
  }
}
```

indexOf the same

The problem is because the spamKeywords in array?

**Comment by AgileNix** [comment]
yes, `spamKeywords` is an array and you should consider this in your code

**Comment by PashaKycher** [comment]
Добрый день.
Мой код:
export const checkSpam = (text, spamKeywords) => {
  let spamKeywordss = [];
  let textt = text.toLowerCase();
  for (let i=0; i<spamKeywords.length; i++){
    spamKeywordss.push(spamKeywords[i].toLowerCase());
  }
  for (let i=0; i<spamKeywordss.length; i++){
    if (textt.includes(spamKeywordss[i]))
      {return true;}
    else
      {return false;}
  }
}
Результат:

1. checkSpam should return a boolean (ОК)

2. checkSpam should return true if the match is found

3. checkSpam should return false if no match is found (ОК)

4. checkSpam should make case insensitive match

Не могу понять свою ошибку.
