### ISSUE TITLE
[TASK] [92]

### ISSUE THREAD

**Issue by gelouuu** [AgileNix/coderslang-feedback#113]
### What is your question?
I already installed in my node.js command prompt the readline sync but I still can't import it in my code. What syntax should I put to import readline-sync?
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ /] Yes

### The output of the terminal with an error if exists
```
//helper.js
    export const askNameAndGreet = () => {
    const readlineSync = require('readline-sync');
    const name = readlineSync.question('Please enter your name: ');
    console.log(`Hello, ${name}!`);
    }
```
```
//package.json
{
  "name": "solution",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}
```
```
//solution.js
import { askNameAndGreet } from './helper.js'

askNameAndGreet();

```
![Screenshot (27)](https://user-images.githubusercontent.com/80969800/111804818-68278c80-890b-11eb-9a30-27bee3a4cb2b.png)

**Comment by AgileNix** [comment]
Hey @gelouuu here's what you're looking for => [how to import an npm module](https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/)

**Comment by gelouuu** [comment]
> Hey @gelouuu here's what you're looking for => [how to import an npm module](https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/)

Thank you! I already finished the task.

**Comment by gelouuu** [comment]
> Hey @gelouuu here's what you're looking for => [how to import an npm module](https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/)
