### ISSUE TITLE
Task 154

### ISSUE THREAD

**Issue by quantumbaze33** [AgileNix/coderslang-feedback#114]
### How have you realized this? I have isolated the 'start' variable and realized that the solution.js has already declared it. 
start variable is fed to the function startsWith(). But the second console.log refuses to read the start variable, which is later fed to the parent function as 's'. 

I realize no matter what, the "console.log(words.filter(startsWith('go')))" fails to be processed..

Do the parameter [start] understands whether a letter or two letters is fed to it? I have tried to make the parameter [start] to capture "go" with the below trials. 

### What solutions have you tried to solve the task?

I have used conditional statements to capture the start variable (by extraction and limitation) of 'go' 
some, that i have tried include:

```javascript

if (s[i] === start | s[i] === 'go')
if (s[i] === start | s[i] === start.startsWith('go'))
if (s[i] === start | s[i] === start.match('go')
if (s[i] === start.match(0, 2)){
if (s[i] === start.substr(0, 2)){
if (s[i] === start | s[i] === start.substr(0, 2)){
if (s[i] === start | start === start.match(/^go/)

```

### Your code
```javascript
export const startsWith = (start) => {

  return (s) => {

    for ( var i = 0; i < s.length; i++){
      
      if (s[i] === start){
          return true;
        }else{
          return false;
      }
    }
    
  }
  
}

```

### The output of the terminal with an error if exists

![154](https://user-images.githubusercontent.com/80545345/111808097-f54eef00-88d3-11eb-9dfc-98717108dd90.PNG)

PS C:\Users\leadzeal\Desktop\Road_To_Fullstack> node c:/Users/leadzeal/Desktop/Road_To_Fullstack/task154/solution.js
[
  'good',   'god',
  'goblin', 'grand',
  'giga',   'giggle',
  'global'
]
[]
[ 'force', 'function' ]
PS C:\Users\leadzeal\Desktop\Road_To_Fullstack>

**Comment by AgileNix** [comment]
@quantumbaze33 parameters can't "understand" anything. It's up to your function to implement the desired functionality. In this case, your check is incorrect. I suggest not reinventing the wheel and using the built-in string function [startsWith](https://learn.coderslang.com/0004-built-in-string-functions-in-js/)

**Comment by quantumbaze33** [comment]
Thank you for the hint.. I applied and got the 'right result' but it refused to pass. 

I will quote two part of the instruction of this task and try to interpret with my own understanding.. 

Instruction 1:  it should accept a single parameter "start" and return a function that takes a string "s" and checks if "s" starts with s. 

My interpretation is this code : 

```javascript
if (start === 'g') {
        return s.startsWith ('g');
```

Instruction 2: if "s" passes the check, the closure should return true, otherwise - false

My interpretation: The true and false you refer here, I assume you meant it in a implicit scope, rather than having us print out true or false on the screen. If this a wrong assumption, please clarify me. 

I used the below code and got the solution.js to work properly. I have also attached other files. Please I appreciate your help, and the getting it 'right' is not really the thrill here, but to understand what is **expected** of me and to **deliver** that expectation.

```javascript
export const startsWith = (start) => {

  return (s) => {

      if (start === 'g') {
        return s.startsWith ('g');
      }
        else if (start === 'go'){
          return s.startsWith ('go');
      }
        else if (start === 'f'){
        return s.startsWith ('f');
      }
      
    }   
  
}

```

![154_1](https://user-images.githubusercontent.com/80545345/111899308-16c2ee80-8a2c-11eb-864d-a82f7fc9e8f4.PNG)

**Comment by AgileNix** [comment]
@quantumbaze33 it's expected that `startsWith` works with any input and isn't limited to the letters `g`, `go` or `f`. Try to replace all the hardcoded characters and only work with the params `s` and `start`.

If you're blocked, I suggest proceeding to other tasks and coming back later.

I can't give you any more hints as it will mean me solving the task instead of you. This way you won't learn much.
The struggle is growth.

**Comment by quantumbaze33** [comment]
Thank you, code master. I got it to work.
