### ISSUE TITLE
LECTURE 218 (code tabulations)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#115]
![image](https://user-images.githubusercontent.com/18144023/111880909-07598c00-89bf-11eb-9b01-85029a56decb.png)

![image](https://user-images.githubusercontent.com/18144023/111880877-e3964600-89be-11eb-8e0e-cc0ae2c8cbf5.png)

![image](https://user-images.githubusercontent.com/18144023/111880871-df6a2880-89be-11eb-98d9-0a7406ac9ffd.png)
![image](https://user-images.githubusercontent.com/18144023/111880883-ec871780-89be-11eb-806b-d9ea57f01fc2.png)
![image](https://user-images.githubusercontent.com/18144023/111880886-f27cf880-89be-11eb-8f4f-1faf5140057f.png)
![image](https://user-images.githubusercontent.com/18144023/111880892-f90b7000-89be-11eb-9fdb-ff2edabfbc5c.png)

**Comment by ssfxate** [comment]
### Check the russian version as well. Same problems.

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report!
