### ISSUE TITLE
TASK 2183 (typo)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#116]
This is a highlight color `#78B3AB` from the description. Looks like a real highlight color.
![image](https://user-images.githubusercontent.com/18144023/111896219-e6c61c00-8a28-11eb-90ff-b9c75c8d977e.png)

This is a wrong color from the assertion, looks like not a highlight one `#38287F`
![image](https://user-images.githubusercontent.com/18144023/111896233-0c532580-8a29-11eb-94e1-f8ba53c159e6.png)

![image](https://user-images.githubusercontent.com/18144023/111896179-ab2b5200-8a28-11eb-9b09-90e2f5189afe.png)
![image](https://user-images.githubusercontent.com/18144023/111896402-76b89580-8a2a-11eb-9c42-dd282907fd21.png)

It passed, but probably the assertion's color-code has a mistake.

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report!
