### ISSUE TITLE
Test suite failed to run syntax error for Task 125

### ISSUE THREAD

**Issue by emmaxy07** [AgileNix/coderslang-feedback#117]
My solution which I'm not sure is correct is not being submitted whenever I try to.

**Comment by AgileNix** [comment]
@emmaxy07 Could you post your code? It will be automatically copied when you click "Help", then just past it here as a comment.

**Comment by emmaxy07** [comment]
## Task: 125

## User implementation 

  #### task125/helper.js
  ```js
  export const getBMICategory = (bmi) => {
  if(bmi <= 18.5){
  return 'Underweight';
  } else if(18.5 < bmi < 25 ){
    return 'Normal weight'
  } else if(25 = bmi < 30){
    return Overweight
  } else if(bmi >= 30){
    return Obesity
  }
}
  ```
        
  #### task125/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task125/solution.js
  ```js
  /**
 * Implement the function `getBMICategory(bmi)` in helper.js. It should accept a single parameter `bmi` and
 * return the string representation of the body mass index category based on the following rules:
 * - **Underweight** = 18.5 or less
 * - **Normal weight** = greater than 18.5 and less than 25
 * - **Overweight** = starting at 25 and less than 30
 * - **Obesity** = 30 or greater
 * */

import { getBMICategory } from './helper.js';

console.log(getBMICategory(10));    // Underweight
console.log(getBMICategory(20));    // Normal weight
console.log(getBMICategory(40));    // Obesity

  ```

**Comment by AgileNix** [comment]
@emmaxy07 so, the issues here are:
1. quotes around the string you return from a function
2. the comparison like `25 = bmi < 30` won't work and should be fixed as described in the lecture
3. make sure that the conditions in if statements are correct, i.e. `starting at 25 and less than 30` should translate to
```js
if (bmi >= 25 && bmi < 30)
```

**Comment by vikoko16** [comment]
## Task: 125

  
  
  
  
  
  
  ## Test result 

  - [x] {
  "en": "`getBMICategory` should be exported from the 'helper.js' file",
  "ru": "`getBMICategory` нужно экспортировать из файла 'helper.js'"
}
        
  - [x] {
  "en": "`getBMICategory` should be a 'function'",
  "ru": "`getBMICategory` должна быть функцией"
}
        
  - [x] {
  "en": "`getBMICategory` should return a string",
  "ru": "`getBMICategory` должна возвращать строку"
}
        
  - [x] {
  "en": "`getBMICategory` should return `Underweight` if bmi is less than 18.5",
  "ru": "`getBMICategory` должна возвращать `Underweight`, если bmi меньше 18,5"
}
        
  - [x] {
  "en": "`getBMICategory` should return `Normal weight` if bmi is greater than 18.5 and less than 25",
  "ru": "`getBMICategory` должна возвращать `Normal weight`, если bmi больше 18,5 и меньше 25"
}
        
  - [ ] {
  "en": "`getBMICategory` should return `Overweight` if bmi is starting at 25 and less than 30",
  "ru": "`getBMICategory` должна возвращать `Overweight`, если bmi начинается с 25 и меньше 30"
}
        
  - [ ] {
  "en": "`getBMICategory` should return `Obesity` if bmi is 30 or more",
  "ru": "`getBMICategory` должна возвращать `Obesity`, если bmi составляет 30 или больше"
}
        
## User implementation 

  #### task125/helper.js
  ```js
  export const getBMICategory = (bmi) => {
  if (bmi<= 18.5){
  return 'Underweight';
} else if (18.5<bmi<25) {
  return 'Normal weight';
} else if (bmi >= 25 && bmi < 30) {
  return 'Overweight';
} else if (bmi>=30){
  return 'Obesity';
}
};
  ```
        
  #### task125/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task125/solution.js
  ```js
  /**
 * Implement the function `getBMICategory(bmi)` in helper.js. It should accept a single parameter `bmi` and
 * return the string representation of the body mass index category based on the following rules:
 * - **Underweight** = 18.5 or less
 * - **Normal weight** = greater than 18.5 and less than 25
 * - **Overweight** = starting at 25 and less than 30
 * - **Obesity** = 30 or greater
 * */

import { getBMICategory } from './helper.js';

console.log(getBMICategory(10));    // Underweight
console.log(getBMICategory(20));    // Normal weight
console.log(getBMICategory(40));    // Obesity

  ```

**Comment by vikoko16** [comment]
Hi, I really don't understand, where my problem

**Comment by ssfxate** [comment]
Change this 18.5​<​bmi​<​25 to bmi>18.5 && bmi​<​25 first of all

**Comment by AgileNix** [comment]
@vikoko16 just as @ssfxate suggests, you should compound the comparisons by using the `&&` operator, so `18.5<bmi<25` becomes `bmi > 18.5 && bmi​ <​ 25`.

If this issue is resolved, please close it.

**Comment by vikoko16** [comment]
Thanks a lot for help
