### ISSUE TITLE
[TASK] [122]

### ISSUE THREAD

**Issue by gelouuu** [AgileNix/coderslang-feedback#118]
### What is your question?
What to do with that error?
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ ] Yes

## Test result 

  - [x] {
  "en": "`getLesserEvil` should be exported from the 'helper.js' file",
  "ru": "`getLesserEvil` нужно экспортировать из файла 'helper.js'"
}
        
  - [x] {
  "en": "`getLesserEvil` should be a function", 
  "ru": "`getLesserEvil` должна быть функцией"
}
        
  - [x] {
  "en": "`getLesserEvil` should return the object",
  "ru": "`getLesserEvil` должна возвращать объект"
}
        
  - [ ] {
  "en": "The `getLesserEvil` function  should compare the `evilFactor` of two object and return the one where it's the smallest",
  "ru": "Функция `getLesserEvil` должна сравнивать `evilFactor` двух объектов и возвращать тот, где он наименьший"
}
        
#### task122/helper.js
  ```js
  export const getLesserEvil = (threat1, threat2) => {
  if (threat1 <= threat2) {
    return threat1;
  } else {
    return threat2;
  }
}
  ```
        
  #### task122/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task122/solution.js
  ```js
  /**
 * Sometimes, there isn't a good choice and we need to choose the lesser evil.
 *
 * Implement a function **getLesserEvil** that takes two objects, compares them by the field **evilFactor** and
 * returns the one which the smaller **evilFactor**.
 * */

import { getLesserEvil } from './helper.js';

const globalWarming = {
  description: 'Global warming risk',
  evilFactor: 10,
}

const aiThreat = {
  description: 'The AI threat to humanity',
  evilFactor: 1,
}

const globalPandemic = {
  description: 'Mass extinction from the global pandemic',
  evilFactor: 3,
}

console.log(getLesserEvil(globalWarming.evilFactor, globalPandemic.evilFactor));
console.log(getLesserEvil(aiThreat.evilFactor, globalPandemic.evilFactor));
  ```
        
![Screenshot (68)](https://user-images.githubusercontent.com/80969800/112444465-05aa1280-8d89-11eb-8649-f3d264d51a6b.png)

**Comment by AgileNix** [comment]
You should get deeper into the threat objects and analyze the `evilFactor` property.

**Comment by AgileNix** [comment]
@gelouuu closing this issue as stale

**Comment by NurNas0502** [comment]
Thanks. It helped me

**Comment by NurNas0502** [comment]
> Thanks. It helped me



> Thanks. It helped me

No, not really worked. The same problem

**Comment by AgileNix** [comment]
@NurNas0502 try something like
```js
if (threat1.evilFactor < threat2.evilFactor)
```
