### ISSUE TITLE
[TASK] [NUMBER]90

### ISSUE THREAD

**Issue by Dim123T** [AgileNix/coderslang-feedback#119]
Greetings! I was trying to do Job 90 of importing constants from a file and displaying those constants on the screen. Can't figure out where the error is? I acted in accordance with the lecture. Thank you for your help.

```
export const API_URL = "http://localhost:8080";
export const MAX_THREADS = 8;

import { API_URL, MAX_THREADS } from '../constants';

console.log(API_URL);
console.log(MAX_THREADS);
```
my result: 
SyntaxError: Identifier 'API_URL' has already been declared
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:47:21)

**Comment by IlyasMirzaaliev** [comment]
импорт - {API_URL, MAX_THREADS} - от '.. /константы';

**Comment by ssfxate** [comment]
Hey @Dim123T. Could you please show your code separated by files?
Something like you can find in https://github.com/AgileNix/coderslang-feedback/issues/112

**Comment by Dim123T** [comment]
Greetings! I was trying to do Job 90 of importing constants from a file and displaying those constants on the screen. Can't figure out where the error is? I acted in accordance with the lecture. Thank you for your help.

**Comment by AgileNix** [comment]
@Dim123T so, the issues here is that the constants should only be declared in the `constants.js` and then imported into `solution.js`.

Remove the lines
```js
export const API_URL = "http://localhost:8080";
export const MAX_THREADS = 8;
```
from solution JS and place them in `constants.js`.
