### ISSUE TITLE
TASK 143

### ISSUE THREAD

**Issue by w0rstR** [AgileNix/coderslang-feedback#12]
Problems:

1. extractNumber should return a number

2. extractNumber should correctly extract regular numbers

TERMINAL:
59.99
1.35
1
13245

solution 
 ```
console.log(extractNumber('$59.99'));
console.log(extractNumber('EUR 1.35'));
console.log(extractNumber('1 BTC'));
console.log(extractNumber('agdflhwet galsdf 13245 sdflgkhytaol chalsdf'));
 ```
  ```export const extractNumber = (s) => {
   const f = s.match(/[+-]?\d+(\.\d+)?/g)[0]
   return f
  ```

**Comment by AgileNix** [comment]
@w0rstR `extractNumber` returns a string in your case, read https://js.coderslang.com/lecture/14 once again

**Comment by Kotsios-10** [comment]
wait what's in the parentheses? 
`const f = s.match(/[+-]?\d+(\.\d+)?/g)[0]`

**Comment by AgileNix** [comment]
@Kotsios-10 it's called a `regular expression`, don't worry about it yet. It will be covered in future lectures.

@w0rstR I'm closing this issue for the lack of activity
