### ISSUE TITLE
[TASK] [96]

### ISSUE THREAD

**Issue by bizz1** [AgileNix/coderslang-feedback#120]
### What is your question?
my codes runs very well on the console but can't pass through the submission phase
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

**Comment by ssfxate** [comment]
Hey @bizz1. Attach your code please.

**Comment by AgileNix** [comment]
@bizz1 The code is automatically copied when you click `help` in VSCode. Feel free to reopen this issue and paste it into description or a separate comment if you still have issues with this task.
