### ISSUE TITLE
[TASK] [92]

### ISSUE THREAD

**Issue by ilaydasalt** [AgileNix/coderslang-feedback#121]
// in helper.js file, i got that error: Test suite failed to run TypeError: (0 , _helper.askNameAndGreet) is not a function

//i imported  "import {readlineSync} from './solution.js';" and npm modules at terminal.

import {readlineSync} from './solution.js';

export const askNameAndGreet = () => {
  const name = readlineSync.question('Please enter your name: ');

  console.log(`Hello, ${name}!`);
}

**Comment by ssfxate** [comment]
@ilaydasalt, due to not enough information I'd suggest to check all similar issues first.
https://github.com/AgileNix/coderslang-feedback/issues?q=readlineSync

**Comment by AgileNix** [comment]
@ilaydasalt closing this one as a duplicate
