### ISSUE TITLE
[TASK] [92]

### ISSUE THREAD

**Issue by ilaydasalt** [AgileNix/coderslang-feedback#122]
### What is your question?
i already import modules but couln't find the solution

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
-  Yes

### What solutions have you tried to solve the task?
import and install the  npm module

### Your code
//helper.js
import {readlineSync} from './solution.js';

export const askNameAndGreet = () => {
 // const readlineSync = require('readline-sync');
  const name = readlineSync.question('Please enter your name: ');

  console.log(`Hello, ${name}!`);
}

//solution.js
/**
 * The code is broken.
 *
 * You need to install the module readline sync and import it
 *
 * Only one import string should be added to helper.js.
 *
 * Don't change solution.js.
 * */

import { askNameAndGreet } from './helper.js'

askNameAndGreet();

//json
{
  "name": "solution",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

### The output of the terminal with an error if exists
Test suite failed to run TypeError: (0 , _helper.askNameAndGreet) is not a function

**Comment by AgileNix** [comment]
@ilaydasalt could you post the structure of files and folders for this task?

One issue that I see with your import is this one:
```js
import {readlineSync} from './solution.js';
```

you should import `readlineSync` from `readline-sync`, and not from `solution.js`

**Comment by ilaydasalt** [comment]
> you should import `readlineSync` from `readline-sync`, and not from `solution.js`

you mean terminal? i already did that too

**Comment by AgileNix** [comment]
@ilaydasalt The first line of your program should be 
```js
import readlineSync from 'readline-sync';
```
