### ISSUE TITLE
LECTURE 219 (forgotten styles sometimes)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#123]
![image](https://user-images.githubusercontent.com/18144023/112729398-efdd4e80-8f3c-11eb-9c88-4845bfa25d49.png)
![image](https://user-images.githubusercontent.com/18144023/112729401-f370d580-8f3c-11eb-9d2f-d17cff2c7903.png)

![image](https://user-images.githubusercontent.com/18144023/112729514-84e04780-8f3d-11eb-8083-818bc4bab4a0.png)

![image](https://user-images.githubusercontent.com/18144023/112729530-99244480-8f3d-11eb-9244-62b668b14e9d.png)
![image](https://user-images.githubusercontent.com/18144023/112729533-a2151600-8f3d-11eb-997c-0f42018630d9.png)

**Comment by amatiyko** [comment]
@ssfxate fixed.Thank you for report

**Comment by amatiyko** [comment]
@ssfxate fixed.Thank you for report
