### ISSUE TITLE
TASK 2202 (something wrong with the visual result of the task)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#125]
Is it really the expected result?
![image](https://user-images.githubusercontent.com/18144023/113443311-632e0700-93fa-11eb-94c4-b339fc395f7c.png)

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Flexbox</title>
    <style>
      h2 {
        text-align: center;
        font-family: Tahoma;
      }
      .container {
        display: flex;
        flex-direction: column;
        justify-content: space-evenly;
        align-items: center;
        height: 200px;
        font-weight: bold;
        font-style: italic;
        font-size: 20px;
        font-family: Tahoma;
      }
      .item {
        background-color: rgb(255, 198, 0);
        padding: 40px;
      }
    </style>
  </head>
  <body>
    <h2>Things I'm learning</h2>
    <div class="container">
      <div class="item">HTML</div>
      <div class="item">CSS</div>
      <div class="item">JS</div>
    </div>
  </body>
</html>
```
![image](https://user-images.githubusercontent.com/18144023/113443349-793bc780-93fa-11eb-8f2c-001839c9d7e3.png)

**Comment by amatiyko** [comment]
@ssfxate no it, is not the expected result.

Elements must be placed in a row, not in a column.

**Comment by AgileNix** [comment]
@ssfxate You’ve added the CSS property `flex-direction: column;`  thus the result is off.

Our tests don’t handle this situation right now, but we’ll fix it shortly. Thank you for the report.
