### ISSUE TITLE
[TASK] [NUMBER]

### ISSUE THREAD

**Issue by umarahh4u** [AgileNix/coderslang-feedback#126]
I was not be able to procced with my practice after been directed to write the following code on my VSC console.log("Hello World");

**Comment by AgileNix** [comment]
@umarahh4u could you describe your issue in more detail in our [Telegram chat](https://t.me/coderslang_chat) and include a screenshot?

**Comment by umarahh4u** [comment]
I was later able to resolved the issue.

Thanks for your help.
