### ISSUE TITLE
TASK2205 | STAGE 3 (more than just a typo)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#129]
Ru Version
![image](https://user-images.githubusercontent.com/18144023/113909097-f9d63b80-97df-11eb-8eda-5480408fa10d.png)

Eng
![image](https://user-images.githubusercontent.com/18144023/113909133-02c70d00-97e0-11eb-97f2-a1e7dcd49cee.png)

**Comment by ssfxate** [comment]
All tasks work like this right now
![image](https://user-images.githubusercontent.com/18144023/113910779-e5933e00-97e1-11eb-9b14-d5e2a82230f7.png)

**Comment by amatiyko** [comment]
@ssfxate  these two tasks were fixed (TASK2205 - stage 3 and TASK1108). There were typos in json. Thank you

**Comment by ssfxate** [comment]
> @ssfxate these two tasks were fixed (TASK2205 - stage 3 and TASK1108). There were typos in json. Thank you

Check all stages of task 2205 as well please.
