### ISSUE TITLE
task250, Stage 13, a mistake btw the description and an assertion

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#13]
Description (one producer)
```It should only print the producers where the count is greater than 0, plus one producer with the 0 count, to show the user what's their next objective.```
Assertion (all the producers)
```8. updateProducerList should print out all the producers where the count is greater than 0```

So what is the correct solution: to show all producers with count 0 or just the first one?

**Comment by AgileNix** [comment]
There are 2 separate tests:
- print all producers where the count is greater than 0
- print next cheapest producer with zero cost

The task description is aligned with that. `only print the producers` -> means all producers that pass the condition

**Comment by ssfxate** [comment]
Oh, I've read it wrong. Sure, You're absolutely right. There was nothing to claim.
