### ISSUE TITLE
Preloader is stuck

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#134]
When I send a task to the server I see the circle which spin and spin and spin…
![image](https://user-images.githubusercontent.com/18144023/114260051-1db1a100-99db-11eb-998f-cb0487e3ebc9.png)
I can release It only via switching languages via the button 
![image](https://user-images.githubusercontent.com/18144023/114260061-36ba5200-99db-11eb-8c6c-ff4ad0b739ad.png)
I mean, when I'm switching it I see the result of checks, otherwise It's spinning infinitely.

**Comment by AgileNix** [comment]
@ssfxate this stage had one small issue with the internationalization of the hints. Could you test again to check if it's fixed now?

**Comment by ssfxate** [comment]
Yes. It is.
