### ISSUE TITLE
En Ru switcher font styles

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#135]
It's readable
![image](https://user-images.githubusercontent.com/18144023/114260105-7d0fb100-99db-11eb-9c1c-fdb1f05d9790.png)

This one isn't readable
![image](https://user-images.githubusercontent.com/18144023/114260110-89940980-99db-11eb-9162-345dd1ebe5c7.png)

**Comment by amatiyko** [comment]
@ssfxate can you please try to reload the vscode and check this issue again

**Comment by ssfxate** [comment]
It's still there.
I've run the stage and check the switcher after that.
![image](https://user-images.githubusercontent.com/18144023/114595633-4796ec00-9c97-11eb-9d83-0edcec1349a4.png)

**Comment by amatiyko** [comment]
@ssfxate ok, but have you tried to close the vscode, open it again and check the switcher then? Just checking the task won't probably fix the issue, but a full vscode reload can.

**Comment by ssfxate** [comment]
When re-opened it, It works well, but I'm gonna watch it in a period. Keep in touch.

**Comment by AgileNix** [comment]
@ssfxate does the issue still appear in the vscode extension?

**Comment by ssfxate** [comment]
@AgileNix, nope. It's not. Thank you.
