### ISSUE TITLE
TASK1108 | STAGE 7

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#136]
### What is your question?
It works via my terminal but can't pass the checks.
I've done all by the instructions. What have I missed or done wrong? Could help me to realise it?

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What solutions have you tried to solve the task?
```javascript
// functions.js
import { sleep } from './helper.js';

export const funkyLog = ({ delay, randomized }) => {
    return s => {
        writeLog(s, delay, randomized);
    }
}

const writeLog = async (s, delay, randomized) => {
    [...s].every(async letter => {
        process.stdout.write(letter);
        await sleep(randomized ? Math.random(delay) : delay);
    });
    process.stdout.write(`\n`);
}

// solution.js
import { funkyLog } from './functions.js';

const message = `
Hello, world 👋!

Let's make our Console Output Fun and Interactive in JavaScript and Node.js 🚀
`;

const log = funkyLog({ delay: 100, randomized: true })

log(message);

```

### Statuses of the checks
❌ 1. The function funkylog should return a function that will be used as as logger.
❌ 2. Замыкание, которое вернет funkylog({delay, randomized}) должно вызывать sleep(delay) столько раз, сколько символов в логгируемой строке. (https://github.com/AgileNix/coderslang-feedback/issues/133)

### The output of the terminal with an error if exists
```
 ~/Documents/Coderslang$ node /home/vadim/Documents/Coderslang/task1108/solution.js

Hello, world 👋!

Let's make our Console Output Fun and Interactive in JavaScript and Node.js 🚀

 ~/Documents/Coderslang$

**Comment by AgileNix** [comment]
@ssfxate the only issue with your code is the name of the function. It should be `funkylog` instead of the `funkyLog`.

**Comment by ssfxate** [comment]
It's passed. Thank you.
