### ISSUE TITLE
[TASK] [NUMBER]

### ISSUE THREAD

**Issue by Kym4uk** [AgileNix/coderslang-feedback#139]
### What is your question?
 can't install Readline-sync 

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ yes] Yes

### The output of the terminal with an error if exists
HP@DESKTOP-KPV9PME MINGW64 /c/Сергій/jscoderslang
$ node c:/Сергій/jscoderslang/task92/solution.js
file:///c:/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9/jscoderslang/task92/helper.js:3
import readlinesync  from 'readlinesync ';
       ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
←[90m    at Loader.moduleStrategy (node:internal/modules/esm/translators:147:18)←[39m

**Comment by Kym4uk** [comment]
$ node c:/Сергій/jscoderslang/task92/solution.js
file:///c:/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9/jscoderslang/task92/helper.js:2
  const name = readlineSync.question('Please enter your name: ');
               ^

ReferenceError: Cannot access 'readlineSync' before initialization
    at askNameAndGreet (file:///c:/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9/jscoderslang/task92/helper.js:2:16)
    at file:///c:/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D0%B9/jscoderslang/task92/solution.js:13:1     
←[90m    at ModuleJob.run (node:internal/modules/esm/module_job:154:23)←[39m
←[90m    at async Loader.import (node:internal/modules/esm/loader:166:24)←[39m
←[90m    at async Object.loadESM (node:internal/process/esm_loader:68:5)←[39m

**Comment by ssfxate** [comment]
You should place import line to the top of the file.
It initialize the module first.

**Comment by Kym4uk** [comment]
yes/ok-Work my cod

**Comment by AgileNix** [comment]
@Kym4uk is your issue resolved? @ssfxate suggested a good solution. I can also add that big/small letters are different in JS
Your import should look like this.
```js
import readlineSync from 'readline-sync ';
```
