### ISSUE TITLE
task250, stage 13, I've got a question

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#14]
All checks passed except one

PASSED 1. updateProducerList should be exported from functions.js
**FAILED** (Why) 2. updateProducerList should be called once from handleKeyPress if isProducerListUpdated is false
PASSED 3. updateProducerList should not be called from handleKeyPress if isProducerListUpdated is true
PASSED 4. updateProducerList should start printing at the beginning of the fifth line by calling moveTo(1, 5)
PASSED 5. handleKeyPress arguments should be forwarded into updateProducerList
PASSED 6. checkInitCompleted should change the value of isProducerListUpdated to false
PASSED 7. updateProducerList should print out the producer information in expected format using a single string
PASSED 8. updateProducerList should print out all the producers where the count is greater than 0
PASSED 9. updateProducerList should print one extra producer with the 0 count and next cost value.

```javascript
// handlers.js
import { updateGold, checkInitCompleted, updateProducerList } from './functions.js';
export const handleKeyPress = (term, state) => {
   return (name, matches, data) => {
        const code = String.fromCharCode(data.code);
        const producers = state.producers;

        if (state.gold >= 10 && !state.isInitCompleted) {
            checkInitCompleted(term, state);
            state.isInitCompleted = true;
        }

        if (code.toLowerCase() === 'g') {
            state.gold++;
        }

        if (Number.isInteger(+code)) {
            if (!state.isProducerListUpdated) {
                updateProducerList(term, state);
                state.isProducerListUpdated = true;
            }

            for (const producer of producers) {
                if (producer.id !== +code) continue;;
                if (state.gold < producer.cost) continue;;

                producer.count++;
                state.gold -= producer.cost;
                producer.cost *= producer.growthRate;
                state.productionRate += producer.baseProduction;
            }
        }
    };
};

export const handleStateChange = (term, state) => {
    return () => updateGold(term, state);
};
```

**Comment by AgileNix** [comment]
Try to avoid nested `if` statements and simplify your code whenever possible.

If the flag `isProducerListUpdated` is set to false, you should always call `updateProducerList`. There shouldn't be any extra conditions like the one you have in your code.

**Comment by ssfxate** [comment]
I was confused by the requirement of `Good examples might be the transition from the initial welcome message in checkInitCompleted or a purchase of a new producer.`.

That's why I tried to place it in any certain action, instead of the body of `handleKeyPress`.
