### ISSUE TITLE
[TASK] [130

### ISSUE THREAD

**Issue by lorelamehdi** [AgileNix/coderslang-feedback#141]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

**Comment by AgileNix** [comment]
@lorelamehdi please post your code and describe the problem. Otherwise, it's impossible to help you.

**Comment by lorelamehdi** [comment]
So it actually prints numbers from 0 to 99, and they are 100 strings and i used a while loop but it still wont turn green...
thank you in advance
![image](https://user-images.githubusercontent.com/82394344/114775392-88fbca00-9d71-11eb-90ba-dbb161a6bb0a.png)
![image](https://user-images.githubusercontent.com/82394344/114775450-9b760380-9d71-11eb-9910-9e75101ede54.png)

**Comment by ssfxate** [comment]
Have you tried to sumbit task after you made the code works well?

**Comment by DmChewbacca** [comment]
i have same problem too

**Comment by AgileNix** [comment]
@DmChewbacca @lorelamehdi move `let i = 0;` into the function.
