### ISSUE TITLE
The gist

### ISSUE THREAD

**Issue by DmChewbacca** [AgileNix/coderslang-feedback#142]
### The output of the terminal with an error if exists
![131](https://user-images.githubusercontent.com/53597398/114896503-af247700-9e10-11eb-881e-65ec571cb2a7.jpg)
![131_2](https://user-images.githubusercontent.com/53597398/114896506-b055a400-9e10-11eb-922e-9fcdda3d696a.jpg)

**Comment by AgileNix** [comment]
@DmChewbacca thank you, we've fixed the tests for this task. The issue with your code is that `let i = 0;` should be outside of the loop.
