### ISSUE TITLE
[TASK] [132]

### ISSUE THREAD

**Issue by vikoko16** [AgileNix/coderslang-feedback#143]
## Task: 132

  Hi, I need help
  
  
  ## Test result 

  - [x] {
  "en": "`getLocale` should be exported from the 'functions.js' file",
  "ru": "`getLocale` нужно экспортировать из файла 'functions.js'"
}
        
  - [x] {
  "en": "`getLocale` should be a function",
  "ru": "`getLocale` должна быть функцией"
}
        
  - [x] {
  "en": "`getLocale` should return the string `en` if the locale isn't found in `knownLocales`",
  "ru": "`getLocale` должна возвращать строку `en`, если локаль не найдена в `knownLocales`"
}
        
  - [ ] {
  "en": "`getLocale` should return the locale if it's found in `knownLocales`",
  "ru": "`getLocale` должна возвращать локаль, если она найдена в `knownLocales`"
}
        
#### task132/functions.js
  ```js
  export const getLocale = (userConfig, knownLocales) => {
  for (let i = 0; i < knownLocales.length; i++) { 
  if (i === userConfig.locale) { 
  return userConfig.locale;
} else {
  return 'en';
}
}
};

  ```
        
  #### task132/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task132/solution.js
  ```js
  /**
 * Fix the function `getLocale`.
 *
 * It should return userConfig.locale if it's found in knownLocales.
 *
 * Otherwise, it should return the string `en`.
 * */

import { getLocale } from './functions.js';

const knownLocales = ['en', 'ru', 'es', 'it', 'fr'];
const userConfig1 = {locale: 'en'};
const userConfig2 = {locale: 'ru'};
const userConfig3 = {locale: 'ws'};

console.log(getLocale(userConfig1, knownLocales));  // en
console.log(getLocale(userConfig2, knownLocales));  // ru
console.log(getLocale(userConfig3, knownLocales));  // en
  ```

**Comment by AgileNix** [comment]
@vikoko16 the problem is here
```js
if (i === userConfig.locale)
```
You're comparing a number to a string.

**Comment by marishgo** [comment]
Hello. I also ran into a problem. I don’t understand what’s wrong. Help me please.

export const getLocale = (userConfig, knownLocales) => {
   for (i = 0; i < knownLocales.length; i++)
   if (i = knownLocales) {
   return userConfig.locale;
} else {
     return 'en';
   }
}

**Comment by AgileNix** [comment]
@marishgo The start is good
```js
for (i = 0; i < knownLocales.length; i++)
```
But the comparison is wrong
```js
if (i = knownLocales) {
```

Try to start loop through known locales `knownLocales[i]` and check each item against user's locale `userConfig.locale`.
