### ISSUE TITLE
Task [138]

### ISSUE THREAD

**Issue by nicomowarsaw** [AgileNix/coderslang-feedback#144]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [Y] Yes

### My code for task 138 : 

export const pow = (x, y) => {
  if (y == 0) { return 1;
  }
  let result = x;
  let count = 1;
  while (count < y){
    result *= x;
    count ++;
  }
  return result;
}

### Status
FAILED
Exceeded execution timeout of 40 seconds

**Comment by AgileNix** [comment]
@nicomowarsaw there's no need to run the loop if `x` is `0` or `1`. Optimize the algorithm to solve this task.
