### ISSUE TITLE
[TASK] [92]

### ISSUE THREAD

**Issue by felly-hoscky** [AgileNix/coderslang-feedback#145]
how can if fix this  Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'readline-sync' imported from d:\CODERSLANGS\task92\helper.js
yet the module was succesfully installed
as shown below
DELL LATITUDE 3440@DESKTOP-GRQVKUQ MINGW64 ~/desktop/coderslangs/task92
$ npm install readline-sync
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN solution@1.0.0 No description
npm WARN solution@1.0.0 No repository field.

+ readline-sync@1.4.10
added 1 package from 1 contributor and audited 1 package in 3.845s
found 0 vulnerabilities

DELL LATITUDE 3440@DESKTOP-GRQVKUQ MINGW64 ~/desktop/coderslangs/task92

### What solutions have you tried to solve the task?
i tried to import it like it is shown below but failed to work
### The output of the terminal with an error if exists
this is the output of the terminal

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'readline-sync' imported from d:\CODERSLANGS\task92\helper.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by nicschwartz** [comment]
I was having this issue... but have another related to an unexpected {

`NICSchwartzMBP:Coderslang Project nicschwartz$ node /Users/nicschwartz/Documents/Coderslang\ Project/task92/solution.js
file:///Users/nicschwartz/Documents/Coderslang%20Project/task92/helper.js:2
  import { REDLINE_SYNC } from './solution.js';
         ^

SyntaxError: Unexpected token '{'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)`

helper.js looks like
`export const askNameAndGreet = function() {
  import { REDLINE_SYNC } from './solution.js';
  const name = readlineSync.question( 'Please enter your name: ' );
  console.log(`Hello, ${name}!`);
}
`

**Comment by nicschwartz** [comment]
@felly-hoscky maybe try installing readline-sync ? 

`npm install readline-sync`

**Comment by AgileNix** [comment]
@nicschwartz the import is incorrect. Please read this [short article](https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/)

If you still have trouble with this task, skip it and move on. You can get back to it later.
