### ISSUE TITLE
Task 127

### ISSUE THREAD

**Issue by emmaxy07** [AgileNix/coderslang-feedback#148]
I still cannot figure out the solution to task 127.

**Comment by AgileNix** [comment]
@emmaxy07 it's ok. Skip it for now and get back when you're ready for it.

If I give you the solution immediately you won't learn much. Give it some thought, post your code (even if it doesn't fully work) and maybe I can guide you in the right direction.

**Comment by emmaxy07** [comment]
export const oneWillDo  = (x, y, z) => { {
    return x===y===z ? true : false 
  }
}

That's my solution for now.

**Comment by Vyzhimov** [comment]
@emmaxy07, try using the operator "||".

**Comment by AgileNix** [comment]
@emmaxy07 ternary operator is excessive here. Follow the advice from @Vyzhimov

**Comment by Mutidobro** [comment]
Re-read the terms carefully, it helped me)

**Comment by Evgenij-Vasiliev** [comment]
agree with Vyzhimov :
try using the operator "||".

**Comment by ghost123a** [comment]
I quite agree. If you read the instructions again and understand it, the code works easy. Thanks all for the inspiration. Thanks @AgileNix  for giving the push.
