### ISSUE TITLE
task104

### ISSUE THREAD

**Issue by coolfaka** [AgileNix/coderslang-feedback#150]
const toLowerCase = (s) => {
  return s.toLowerCase();
}

const toUpperCase = (s) => {
  return s.toUpperCase();
}

export const createSamples = (s) => {
  return 'toLowerCase' + 'toUpperCase';
}

**Comment by coolfaka** [comment]
/**
 * Implement the function createSamples that takes a string and returns two samples of it, one in lowercase
 * and another one in the uppercase.
 *
 * Samples should be combined, i.e. createSamples('HeLLo') should return the string 'helloHELLO'
 *
 * You must use functions toLowerCase and toUpperCase from the file helper.js
 * */

**Comment by AgileNix** [comment]
@coolfaka You should use the functions, not string values.
Take a look:
```js
return toUpperCase(s) + toUpperCase(s);
```
This is not the right solution, but it should give you an idea of what you should do in this task.
