### ISSUE TITLE
Length of the circle given radius

### ISSUE THREAD

**Issue by Greelloo** [AgileNix/coderslang-feedback#151]
I don't really understand this task. Can someone please explain the task.

## Test result 

  - [x] {
  "en": "`circleLength` should be exported from the file 'helper.js'",
  "ru": "`circleLength` нужно экспортировать из файла 'helper.js'"
}
        
  - [x] {
  "en": "`circleLength` should be a 'function'",
  "ru": "`circleLength` должна быть функцией"
}
        
  - [ ] {
  "en": "Function `circleLength` should return the length of the circle given the radius",
  "ru": "Функция `circleLength` должна возвращать длину круга с учетом радиуса"
}
        
#### task103/helper.js
  ```js
  const PI = 3.14159265359;

export const circleLength = (radius) => {
  return PI * 4 / radius;
}
  ```
        
  #### task103/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task103/solution.js
  ```js
  /**
 * Implement a function circleLength that calculates the length of the circle given its radius
 * */

import { circleLength } from './helper.js';

console.log(circleLength(5));
console.log(circleLength(12));
  ```

**Comment by AgileNix** [comment]
@Greelloo This formula `PI * 4 / radius;` is incorrect. You should google the correct one and fix the function `circleLength`, which should calculate the length of the circle.

**Comment by Greelloo** [comment]
@AgileNix thank your for the tip, I will work on it.
