### ISSUE TITLE
Task145 - Spam Filter

### ISSUE THREAD

**Issue by AgileNix** [AgileNix/coderslang-feedback#152]
Spam filter

Implement the function checkSpam(text, spamKeywords).

It should return true if the text contains any of the `spamKeywords`, otherwise - false.

The comparison should be case insensitive.

for this task my code was this:
```js
export const checkSpam = (text, spamKeywords) => {
text = text.toLowerCase()
for (let i = 0; i<spamKeywords.length;i++){
  if (text.includes(spamKeywords[i]))
  return true;
else {
  return false;
    }
  }
}
```

it returns true and false respectively but I still got these errors 

✅1. checkSpam should return a boolean'

❌2. checkSpam should return true if the match is found

✅3. checkSpam should return false if no match is found

❌4. checkSpam should make case insensitive match

**Comment by AgileNix** [comment]
The problem here is that you've transformed `text` to lower case, but haven't done the same for each of the `spamKeywords`.

**Comment by DarioD99** [comment]
i fixed the code as you said and still got the same error 

export const checkSpam = (text, spamKeywords) => {
text = text.toLowerCase()
for (let i = 0; i<spamKeywords.length;i++){
 spamKeywords[i]=spamKeywords[i].toLowerCase()
  if (text.includes(spamKeywords[i]))
  return true;
else {
  return false;
    }
  }
}

**Comment by AgileNix** [comment]
Let's start by removing the unnecessary assignments.

You don't really need `text =` and `spamKeywords[i]=`.

Then test your code with the `text` and `spamKeywords` array where one of the spam keywords appears in the text, but it's not the first item of the array. Your current implementation only analyses the first item of `spamKeywords` and never gets to the second element.

**Comment by DarioD99** [comment]
if I remove `text =` it doesnt change the `text` to lowercase

**Comment by DarioD99** [comment]
I think i figured it out thank you!
`export const checkSpam = (text, spamKeywords) => {
text = text.toLowerCase()
for (let i = 0; i<spamKeywords.length;i++){
 spamKeywords[i]=spamKeywords[i].toLowerCase()
 
 if (text.includes(spamKeywords[i]))
  return true;

    }
 return false;

  }
`

**Comment by AgileNix** [comment]
@DarioD99 you can do `if (text.toLowerCase().includes(spamKeywords[i]))`
