### ISSUE TITLE
[TASK] [121]

### ISSUE THREAD

**Issue by asdsod** [AgileNix/coderslang-feedback#154]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What solutions have you tried to solve the task?
export const min = (a, b, c) => {
 if (a<=b || a<=c) {
 return a} 
}
второй способ :
export const min = (a, b, c) => {
 if (a<=b || a<=c) {
 return a} else if (a>=b || c>=b) {
   return b
 } else if (a>=c || b>=c) {
   return c
 }
}
### Statuses of the checks при втором способе
ДА1. min нужно экспортировать из файла 'helper.js'

ДА 2. min должна быть функцией

НЕТ 3. Функция min должна возвращать минимальное из 3 чисел

ДА. min не должна возвращать undefined

**Comment by asdsod** [comment]
Приветствую я не могу выполнить эту задачу помогите

**Comment by AgileNix** [comment]
@asdsod try with different values of a, b and c and you'll see the issue

For example:
```if (a<=b || a<=c) {return a}```
Here you return immediately if `a` is less than or equal to `b`. Even if `c` is the smallest element.

**Comment by ghost123a** [comment]
Hello this is the code I wrote for this task and output is giving me the minimum no however task submission is giving me an error

export const min = (a, b, c) => { if (a< b && c)
return a;
 else if (b<a&&c) return b;
else if (c<a&&b) return c;
else return 0;}

**Comment by ViktorNovikov2108** [comment]
Здравствуйте, я не могу понять эту запись: "console.log(`The minimum is ${min(a, b, c)}`);".
Каким образом из строки мы получаем результат функции? Знак "$" - неприпомню в предыдущих лекциях чтобы мы его использовали.
Или просто необходимо допольнительно прочитать информацию о синтаксисе VSCode или это синтаксис JS?
Заранее спасибо.

**Comment by AgileNix** [comment]
@ViktorNovikov2108 Такая запись называется - шаблонная строка. О ней будет в будущих лекциях. В контексте задачи тебе нужно только работать с функцией `min`.
