### ISSUE TITLE
[TASK] 121

### ISSUE THREAD

**Issue by lorelamehdi** [AgileNix/coderslang-feedback#156]
Hello, I have tried various ways of doing the task, it runs, but when i submit it says failed.

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What solutions have you tried to solve the task?
```js
export const min = (a, b, c) => {
  if (a<b && a<c){
    return(a);
  }
    else{
      if (a>b && a<c){
        return (b);
        }
        else if (a>b && a>c){
            if(b<c){
              return(c);
            }
            else {
              return (b);
            }
          }
          else if (a<b && a>c){
            return(c);
          }
       
      }
    }
```

### The output of the terminal with an error if exists
no errors in the terminal.

**Comment by AgileNix** [comment]
@lorelamehdi in general there are 3 possibilities:
1. a is the smallest number - check a <= b && a <= c
2. b is the smallest number - check b <= a && b <= c
3. c is the smallest number - if the two previous conditions were not satisfied, then c is the smallest number

**Comment by asdsod** [comment]
Спасибо так и сделал и все вышло.
но я не доконца понял смысл суть команды <=

**Comment by asdsod** [comment]
я гуглил но что то не понятно там

**Comment by AgileNix** [comment]
@asdsod `<=` - меньше или равно

**Comment by lorelamehdi** [comment]
Done, thank you!
