### ISSUE TITLE
TASK 2222 (default blueviolet isn't the #8a2be2)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#167]
![image](https://user-images.githubusercontent.com/18144023/117316634-6d2ba580-ae91-11eb-9551-049081dc0405.png)

Changed it passed
![image](https://user-images.githubusercontent.com/18144023/117316741-8896b080-ae91-11eb-951a-f6732fb6a745.png)

No requirements to change it.
```
General sibling combinator

The text color in all paragraphs after #secondP must be #01BBE2.
Do not add new classes, identifiers, or inline styles to paragraphs.
Use a common sibling combinator.

**Comment by amatiyko** [comment]
@ssfxate I have fixed the initial file. Thank you for the report!

**Comment by amatiyko** [comment]
@ssfxate I have fixed the initial file. Thank you for the report!
