### ISSUE TITLE
TASK 2223 (typos)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#168]
Electrical appliances? I promise, I won't 😊 
![image](https://user-images.githubusercontent.com/18144023/117317216-fd69ea80-ae91-11eb-909b-2f82af54f427.png)

**Comment by ssfxate** [comment]
![image](https://user-images.githubusercontent.com/18144023/117319036-9baa8000-ae93-11eb-96a6-068258e5a7ae.png)
![image](https://user-images.githubusercontent.com/18144023/117318989-92b9ae80-ae93-11eb-86ac-26ccfe29c440.png)
![image](https://user-images.githubusercontent.com/18144023/117318935-87ff1980-ae93-11eb-9de4-aa8458dd164e.png)
![image](https://user-images.githubusercontent.com/18144023/117318952-8cc3cd80-ae93-11eb-91be-6faade9ac425.png)

**Comment by amatiyko** [comment]
@ssfxate Fixed. Thank you for the report!
