### ISSUE TITLE
TASK 2251 | STAGE 6 (typo)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#174]
Should be "Second" I guess.
![image](https://user-images.githubusercontent.com/18144023/117534620-ea265e80-affa-11eb-90d8-2250c8793808.png)

**Comment by ssfxate** [comment]
![image](https://user-images.githubusercontent.com/18144023/117534797-9f591680-affb-11eb-9b69-cd77f04c6f86.png)

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report
