### ISSUE TITLE
[TASK] [85]

### ISSUE THREAD

**Issue by engamo** [AgileNix/coderslang-feedback#181]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### 
function printUppercaseMessage (message) {
  console.log(message.toUpperCase());
}

get myMessage = `I'm on a path to becoming a JS developer!`;

printUppercaseMessage(myMessage);

### The output of the terminal with an error if exists
';' expected.

**Comment by AgileNix** [comment]
@engamo The problem is that the variable `myMessage` is declared incorrectly. Fix the variable declaration.
