### ISSUE TITLE
The app is stuck in spinning after I've done the last stage of a long task.

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#185]
- It shows no checks' results.
- The spinner (preloader) is spinnging infinitively.
- All tasks' files have been deleted already. It means the last stage of a long task has finished finally.
![image](https://user-images.githubusercontent.com/18144023/118355693-ff126d00-b579-11eb-98df-9e8a9b6008e9.png)

**Comment by amatiyko** [comment]
@ssfxate fixed. There was an issue in the task final description. Thank you for the report!
