### ISSUE TITLE
TASK 350 (no task actually)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#187]
I see It should exist, but actually I've got nothing downloaded (0 new tasks).

![image](https://user-images.githubusercontent.com/18144023/118357300-20775700-b582-11eb-9200-960782455de5.png)
![image](https://user-images.githubusercontent.com/18144023/118357350-6502f280-b582-11eb-8c6e-bb1c4828022f.png)
![image](https://user-images.githubusercontent.com/18144023/118357354-692f1000-b582-11eb-831d-a52dcf56bdaf.png)

**Comment by ssfxate** [comment]
The same thing for the tasks 351 https://js.coderslang.com/tasks/351
![image](https://user-images.githubusercontent.com/18144023/118600759-163f9d80-b7ba-11eb-9e38-e6c51b99c15b.png)

**Comment by amatiyko** [comment]
@ssfxate please check now.

**Comment by ssfxate** [comment]
I got them. 6 new tasks. 1 (350) + 5 (351).
