### ISSUE TITLE
Lecture 101, typos

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#19]
`It can be a console(as in the last problem of the first level "Gold Mine")…`
Missed the space before the bracket

`First, you need to implement a API`
an API

P.S. I'm now sure about the article "the" in these blocks. The same time I'm not so confident in my English to force the point.

Backend - is everything that **the** user does not see. This is a database, a server, a load balancer, a proxy, and many other things.
Frontend - is what **the** user interacts with. It can be a console(as in the last problem of the first level "Gold Mine"), a web application in React.js, and a native mobile application for iOS and Android. Anything that **the** user can directly access.

**Comment by AgileNix** [comment]
Fixed the first 2 points, thank you.

The part related to `the` isn't obvious to me too. It looks ok, so we won't touch it for now.

I usually use `Grammarly` to check the typos and grammar, but it doesn't integrate with the markdown editor that I'm writing Coderslang lectures in. This causes occasional mistakes that we're fixing along the way.
