### ISSUE TITLE
TASK 3××× (Command 'yarn' not found)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#191]
When I try to run locally I've got the error.
![image](https://user-images.githubusercontent.com/18144023/118868769-3fad1600-b8ed-11eb-8a39-0a5fc0a42db8.png)
![image](https://user-images.githubusercontent.com/18144023/118868803-4dfb3200-b8ed-11eb-8ee9-edb950e535b7.png)
![image](https://user-images.githubusercontent.com/18144023/118869840-8cddb780-b8ee-11eb-8c23-2d60ef862d18.png)

I understand the error and the suggestion to fix, but what I've missed that is why I'm getting this error?

VSCode Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic

**Comment by amatiyko** [comment]
@ssfxate I have already created a ticket to fix it - will be done ASAP. For now, you can install the yarn package manager to run tasks

**Comment by ssfxate** [comment]
But actually I've installed Yarn via the https://classic.yarnpkg.com/en/docs/install/#debian-stable instruction instead of the solution from the screenshot `sudo apt install cmdtest`.
