### ISSUE TITLE
TASK 3513 (App.js with no components by default)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#192]
I see the description of the task.
```
Colors
App.js files have a component to rotate a column of three blocks.
The column is guilty of taking care of all the screen - its own flex is 1.
The first block of columns with a blue background, the second - green, the third - yellow.
All three blocks must be equal and completely cover the screen.
```
And simultaneously see no components. I'm still not confident to create it by my own.
```javascript
import React from 'react';

export default function App() {
  return ();
}

```
Just for example the task 3514 has a lot of components to modify them.

I guess, it's just a forgotten file to filled it up.

**Comment by amatiyko** [comment]
@ssfxate I have updated the description a little, so thank you for the report. But the initial content of the `App.js` is correct. You need to finish it by yourself.
