### ISSUE TITLE
TASKS 3××× (.expo folder left after the task has been done)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#193]
When I done any RN task and the folder is going to DONE, some files are left there due to run Expo.
![image](https://user-images.githubusercontent.com/18144023/119249234-9c375c00-bb9f-11eb-8b28-123466c96267.png)

**Comment by ssfxate** [comment]
@AgileNix, I'm getting this every task. My OS is Linux, btw.

Run any RN task locally, consequently run Submit.

**Comment by amatiyko** [comment]
@ssfxate ok, thank you. will try to find out why this issue appears and fix
