### ISSUE TITLE
LECTURE 352 (where is the uri in the source property?)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#196]
https://js.coderslang.com/lecture/352

![image](https://user-images.githubusercontent.com/18144023/120066558-ce552c00-c07f-11eb-945e-5ca7148d5d30.png)
In the task 3524 you're requiring it
![image](https://user-images.githubusercontent.com/18144023/120066582-e75ddd00-c07f-11eb-9917-4e183011eecc.png)

I've checked the RN documentation as well. Uri must be there.
https://reactnative.dev/docs/images#network-images

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report
