### ISSUE TITLE
TASK 3534 (the description and the checks)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#199]
![image](https://user-images.githubusercontent.com/18144023/121240983-929e3b80-c8a3-11eb-9080-546fc3a44fa5.png)
![image](https://user-images.githubusercontent.com/18144023/121240891-7f8b6b80-c8a3-11eb-9bb4-f785d48d5f89.png)

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for the report
