### ISSUE TITLE
Lecture 16, typo

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#2]
An extra space after $ in the code

```javascript
const checkSecurity = (target) => () => {
    console.log (`Checking ${target}'s security ...'`)
}
```

1. Extra `'` at the end of console.log() row before backquote.
2. Extra space after security.

---
`How to delete **sheduled** timeout or interval`

Should be **scheduled**

---
`removes the scheduled **exetution** from the queue.`
Should be **execution**

**Comment by AgileNix** [comment]
Fixed
