### ISSUE TITLE
TASK 3535 | STAGE 1 (the desciption and the checks)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#200]
![image](https://user-images.githubusercontent.com/18144023/121242762-9a5edf80-c8a5-11eb-9da0-3b4392e60ffc.png)
![image](https://user-images.githubusercontent.com/18144023/121242776-9f239380-c8a5-11eb-88f8-c03511112a4f.png)

I guess It should be just 60 without `%` or `px` in both places. I found a similar sentence in the Stage 3 of the same task.
![image](https://user-images.githubusercontent.com/18144023/121248742-75219f80-c8ac-11eb-9259-4e70708e9db1.png)

**Comment by amatiyko** [comment]
@ssfxate I have decided to add `px` and `%` everywhere. Please download tasks to see changes

**Comment by amatiyko** [comment]
@ssfxate can we close this issue or do you have some other questions?
