### ISSUE TITLE
TASK3533 (onChange)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#205]
I have no idea what to do to get it done.
- [x] 1. The <App /> component should have three child elements
- [x] 2. The <App /> component should have two <TextInput> components
- [x] 3. The multiline property of the second TextInput component should be set to true
- [x] 4. The initial value of the second TextInput component should be an empty string
- [ ] 5. The second TextInput component should have onChange prop specified.
- [ ] 6. The onChange callback should change the second TextInput component value.
- [x] 7. The second TextInput component should have same styles as the first one.
- [x] 8. The second TextInput component should have 'Message' placeholder.
```javascript
import React, { useState } from 'react';
import { StyleSheet, Text, TextInput, View, Dimensions } from 'react-native';

export default function App() {
  const [email, setEmail] = useState("");
  const [value, setValue] = useState("");
  // const onChange = e => setValue(e.target.value);

  return (
    <View style={styles.container}>
      <Text style={styles.header}>Leave you feedback</Text>
      <TextInput
        placeholder="Email"
        style={styles.input}
        value={email}
        onChangeText={setEmail}
      />
      <TextInput
        multiline
        placeholder="Message"
        style={styles.input}
        value={value}
        onChangeText={setValue}
        // onChangeText={onChange}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 100,
    backgroundColor: '#56c7c0',
  },
  header: {
    fontSize: 18,
  },
  input: {
    marginVertical: 30,
    borderWidth: 2,
    borderColor: '#ffb900',
    backgroundColor: '#ffffff',
    padding: 10,
    borderRadius: 10,
    width: 0.8 * Dimensions.get('screen').width,
  }
});
```

**Comment by amatiyko** [comment]
@ssfxate you have specified the `onChangeText` prop for the second `TextInput`. But you should specify the `onChange` prop

**Comment by ssfxate** [comment]
@amatiyko Thank you. I've got the difference btw `onChange` and specified `onChangeText`.

`onChange` gives us an event with a lot of things.
![image](https://user-images.githubusercontent.com/18144023/121912566-5c483c80-cd39-11eb-97e0-d807b78d5032.png)

Otherwise `onChangeText` gives just a string.
