### ISSUE TITLE
LECTURE 354 (spaces at the start of some the <code> </code> tags)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#207]
https://js.coderslang.com/lecture/354

![image](https://user-images.githubusercontent.com/18144023/122630085-04f3f480-d0ca-11eb-8a68-9e4b25aa8899.png)
![image](https://user-images.githubusercontent.com/18144023/122630098-1b01b500-d0ca-11eb-939c-28e9081de5ba.png)
![image](https://user-images.githubusercontent.com/18144023/122630100-21902c80-d0ca-11eb-8e68-1fdf77999d03.png)
![image](https://user-images.githubusercontent.com/18144023/122630105-2ce35800-d0ca-11eb-8ed3-6b6bd24d618e.png)
![image](https://user-images.githubusercontent.com/18144023/122630111-3cfb3780-d0ca-11eb-9513-3f3236803540.png)

**Comment by amatiyko** [comment]
@ssfxate fixed
