### ISSUE TITLE
Unknown submission error

### ISSUE THREAD

**Issue by Altyn777** [AgileNix/coderslang-feedback#209]
![image](https://user-images.githubusercontent.com/45104737/122682138-65854d80-d200-11eb-8558-076474e17a37.png)

While trying to check the task 2023, I press submit and the error appears:
Unknown submission error

**index.html**
`<p><h2>London is the capital of Great Britain</h2>, its political, economic and cultural centre. It's one of the largest cities in the world. Its population is more than million people. London is situated on the river Thames.</p>`

**Comment by ssfxate** [comment]
Is it related to the https://github.com/AgileNix/coderslang-feedback/issues/201?

**Comment by Altyn777** [comment]
Yes
