### ISSUE TITLE
Energy, what entity is it?

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#21]
I see that most of the time I have a sort of extra energy (much more than zero, 45 at the moment).

Could you please explain the sense of the energy or give a link to the lecture that I could read diagonally and miss the explanation?

**Comment by ssfxate** [comment]
Is it balanced well?

**Comment by AgileNix** [comment]
Energy is spent when you open new lectures. You earn it by solving tasks.

Your energy is quite high as you've probably solved all tasks.

Most users will have to skip some and we need to make sure, we're not blocking their progress.
