### ISSUE TITLE
TASK 3552 (API)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#215]
English version has miseed the `s` at the end of the `API`
![image](https://user-images.githubusercontent.com/18144023/124648900-7d1b3200-dea0-11eb-9d42-0cb8eee026b0.png)

Russian version has it correctly.
![image](https://user-images.githubusercontent.com/18144023/124648953-8ad0b780-dea0-11eb-8545-571595cc7e73.png)

**Comment by amatiyko** [comment]
@ssfxate fixed, please download tasks again to see changes
