### ISSUE TITLE
TASK 3552 (RNAPIs?)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#216]
What do you mean by this?
![image](https://user-images.githubusercontent.com/18144023/124649195-d84d2480-dea0-11eb-9f4e-97180923f4e3.png)

There are not requrement for this in the description.

```javascript
// App.js
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

import Components from './screens/RNComponents';
import APIs from './screens/RNAPIs';

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="APIs">
        <Stack.Screen name="Components" component={Components} />
        <Stack.Screen name="APIs" component={APIs} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by amatiyko** [comment]
@ssfxate there was an initial bug in `RNAPIs` screen. I have fixed it. To see changes you need to delete this task and download it again. Don't forget to save yours implementation of the `App.js` somewhere before deleting the task.

Please let me know if there still will be any issues.
