### ISSUE TITLE
Suggestion for an improvement of the course

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#22]
Change the page title when we're switching topics.

For now it's the only `CoderslangJS`.
![image](https://user-images.githubusercontent.com/18144023/100271883-43c62f80-2f6b-11eb-9507-16a2ae1b7ff2.png)
 
It'd help me to find an article faster via browser history instead of clicking.

Like I see the sentence `If you're not really sure what I just said, then I suggest going over the lecture on Advanced Functions once again.` I would type `Advanced functions` in the browser to open the topic directly without extra steps that I must do right now to get into it.

**Comment by AgileNix** [comment]
@ssfxate thanks for the feedback. We're not ready to do this yet as the lecture titles might change and we don't want to create confusion.

An even better way would be to add links to the lectures.
