### ISSUE TITLE
TASK 3565 (Change All Stack to Tab)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#222]
All `Stack` should be `Tab`
1. The App component should return NavigationContainer component
2. The NavigationContainer should have one child element
3. The NavigationContainer should have the Tab.Navigator element as child
4. The **Stack**.Navigator should have one child element
5. Both child elements of the **Stack**.Navigator should be the Tab.Screen element
6. The first **Stack**.Screen should have the name prop set to USA
7. The first **Stack**.Screen should have the component prop set to USAStateScreen component imported from screens/USAStateScreen
8. The second **Stack**.Screen should have the name prop set to Canada
9. The second **Stack**.Screen should have the component prop set to CanadaProvincesScreen component imported from screens/CanadaProvincesScreen
10. The USAStateScreen should be rendered initially

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report
