### ISSUE TITLE
TASK 3554 | STAGE 4 (third button?)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#224]
`third button` should be `second button`

          "Let's work on the navigation buttons of the `Comments` screen.",
          "Pressing the first button should take the user to the previous screen.",
          "Use the `goBack` method for this.",
          "Pressing the third button should take the user to the initial stack screen.",
          "Use the `popToTop` method for this."
          
`третей` should be `второй`, by the way `третей` has a syntax error. Should be `третЬей`.

          "Проработаем кнопки навигации экрана `Comments`.",
          "Нажатие первой кнопки должно переводить пользователя на предыдущий экран.",
          "Используй метод `goBack` для этого.",
          "Нажатие третей кнопки должно переводить пользователя на начальный экран стэка.",
          "Используй метод `popToTop` для этого."

**Comment by amatiyko** [comment]
@ssfxate fixed
