### ISSUE TITLE
TASK 3572 (checks / double language)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#230]
- [ ] 1. The <App /> component should have two child nodes
- [ ] 2. The first child node of the <App /> component should be Modal
- [ ] 3. The Modal node should have visible prop initially set to false
- [ ] **4. { "en": "The Modal node should have only one child which is View", "ru": "У Modal должен быть только один дочерний элемент View", }**
- [ ] 5. The View node of the Modal should have flex style set to 1
- [ ] 6. The View node of the Modal should have alignItems style set to center
- [ ] 7. The View node of the Modal should have justifyContent style set to center
- [ ] 8. The View node of the Modal should have backgroundColor style set to white
- [ ] 9. The View node of the Modal should have Button child node with Hide modal title
- [ ] 10. The Button node of the Modal should have onPress prop defined
- [ ] 11. The opened Modal should be closed on the Button node of the Modal press
- [ ] 12. The second child node of the <App /> component should be Button
- [ ] 13. The Button node should have onPress prop defined
- [ ] 14. The Modal should be shown on Show modal Button pressing

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for your report
