### ISSUE TITLE
TASK 3574 (wants no title but where?)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#231]
When you click on the `Confirm agreement` border, an `Alert` should appear **with the title Please confirm.**
Alert should show a message - `Are you agree?` And two buttons - `Sure` and `No, no, no`.
When you click on the first button, a message should appear on the screen - `You have agreed to become super developer.`
When you click on the second - `Alert` should just close.

- [x] 1. The <App /> component should have one child node Button
- [x] 2. The <Button /> should have onPress prop defined
- [x] 3. The onPress prop should call Alert.alert method on Button press
- [x] 4. The Alert.alert method should have only three arguments
- [ ] 5. The first argument of the Alert.alert should be empty string or null
- [x] 6. The second argument of the Alert.alert method should be the Request was successfully sent string
- [x] 7. The third argument of the Alert.alert method should be the Alert buttons array with two items
- [x] 8. The first Alert button should have Sure title
- [x] 9. The first Alert button should have onPress method
- [x] 10. After the first Alert button press the You have agreed to become super developer text should appear
- [x] 11. The second Alert button should have No, no, no title
- [x] 12. The second Alert button should not have onPress method

```javascript
import React, { useState } from 'react';
import { StyleSheet, Button, View, Text, Alert } from 'react-native';

export default function App() {
  const [show, setShow] = useState(false);
  const handleConfirmAgreement = () => Alert.alert(
    "Please confirm", // it can be empty as well, but still can't pass the check
    "Are you agree?",
    [
      {
        title: "Sure",
        onPress: () => setShow(true),
      },
      {
        title: "No, no, no",
      }
    ]
  )
  return (
    <View style={styles.container}>
      <Button
        title="Confirm agreement"
        onPress={handleConfirmAgreement}
      />
      {show && (<Text>You have agreed to become super developer</Text>)}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by amatiyko** [comment]
@ssfxate there was a bug, now should be fixed. Please check and let me know if you any issue

**Comment by ssfxate** [comment]
@amatiyko 
## Unknown submit error
![image](https://user-images.githubusercontent.com/18144023/127158811-b23f0301-d108-45d5-84ad-dac7e331c00a.png)

**Comment by amatiyko** [comment]
@ssfxate you should wait for server update. it takes time

**Comment by ssfxate** [comment]
@amatiyko still the same result.

**Comment by amatiyko** [comment]
@ssfxate `still the same result` - you can't submit the result or test failed?

**Comment by ssfxate** [comment]
> @ssfxate `still the same result` - you can't submit the result or test failed?

Can't submit at all

**Comment by ssfxate** [comment]
Passed now.
