### ISSUE TITLE
[TASKS 1032-1043] No russian translation

### ISSUE THREAD

**Issue by Horuse** [AgileNix/coderslang-feedback#237]
A link to a lecture or quiz or just a task name.
1043,1042,1034,1033,1032 tasks

The quote of the block that contains the typo.
Task details
![image](https://user-images.githubusercontent.com/39675195/131255709-8be88a57-289b-49a8-a06a-7f2f047030d2.png)

Expected result by you mean
Instead of Russian text, English

**Comment by amatiyko** [comment]
@Horuse do you still face this issue (if yes please download tasks and check again)?
