### ISSUE TITLE
task1051, doesn't want to pass

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#24]
PASSED 1. The server should have the `GET /config` route
**FAILED** 2. `GET /config` route should return the object `config` from constants.js
```javascript
import express from 'express';
import { config } from './constants.js';

const server = express();

server.get('/config', (req, res) => {
  return res.send(JSON.stringify(config));
  //send the response here
})

export { server };
```

I've checked the route locally by `localhost:8080/config`. It's really the config object in JSON.
```json
{"gold":29,"title":"CoderslangJS","learningSchedule":["Sunday","Monday","Tuesay","Wednesday","Thursday","Friday"],"focus":100}

**Comment by ssfxate** [comment]
It passed with
```javascript
return res.json(user);
```
But why?

**Comment by AgileNix** [comment]
Because of the response type. In case of `.send` it will be `text/html`. If you want to send back JSON, you should use `res.json()` and the content-type will be set properly.

**Comment by ssfxate** [comment]
I was confused by the article https://js.coderslang.com/lecture/105
![image](https://user-images.githubusercontent.com/18144023/100394731-4437f680-304f-11eb-88c6-eaeba355579f.png)

**Comment by AgileNix** [comment]
It's an oversimplification that's close to a mistake. We'll fix that by adding more information to the lecture.
