### ISSUE TITLE
task127

### ISSUE THREAD

**Issue by RomanLeschenko** [AgileNix/coderslang-feedback#25]
Implement the function oneWillDo in helper.js. It should accept 3 boolean parameters (x, y, z) and

return true, if at least one of them is true
return false otherwise
The function oneWillDo should NOT contain any if statements

How to write without any if statement?

**Comment by AgileNix** [comment]
@RomanLeschenko let's change the task description a bit. You need to accept 3 numbers and return 0 if at least one of them is 0. Can we do this without an `if` statement?
Hint: we need to use one simple mathematical operation.

**Comment by RomanLeschenko** [comment]
@AgileNix 
Thank's, I make it
