### ISSUE TITLE
running code

### ISSUE THREAD

**Issue by vovgreba** [AgileNix/coderslang-feedback#26]
$ node d:/Coderslang/task90/solution.js
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: d:\Coderslang\task90\solution.js
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:899:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)←[39m
←[90m    at internal/main/run_main_module.js:18:47←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}

**Comment by AgileNix** [comment]
Which version of `node` are you using?
If it's less than 14.x, try to update it and let me know if you still have issues.

**Comment by AgileNix** [comment]
@vovgreba I'm closing this issue as it seems that you've resolved it
