### ISSUE TITLE
task1069, 4. The function formatNumber should work properly for numbers less than 999T

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#29]
I've just copied my code from #16 and removed the part of the code which trails `.00` due to the missleading requirements that I mentioned in #28.
```
Formatted 0 looks like 0
Formatted 1 looks like 1
Formatted 100.15 looks like 100.2
Formatted 999 looks like 999
Formatted 10000 looks like 10.00K
Formatted 100000 looks like 100.00K
Formatted 123521 looks like 123.52K
Formatted 10000000 looks like 10.00M
Formatted 1234321 looks like 1.23M
Formatted 12343210000 looks like 12.34B
Formatted 1234321000000 looks like 1.23T
Formatted 123432100000 looks like 123.43B
Formatted 12343210000000 looks like 12.34T
Formatted 1234321000000000 looks like 1.23a
Formatted 12343210000000000 looks like 12.34a
Formatted 12343210000000000000 looks like 12.34b
```
Look on these results. It should pass, but not.
If you still need the code, I laid it in #30.

**Comment by AgileNix** [comment]
The implementation is incorrect. The next suffix after `T` is `aa`, not `a`. Then `ab`, not `b`.

**Comment by ssfxate** [comment]
But here I am asking about the check for 999T and below.

**Comment by AgileNix** [comment]
There was a corner case that we were not handling well enough. The fix will be deployed today.

**Comment by ssfxate** [comment]
4th check is passing now.
