### ISSUE TITLE
task250, stage 3, description mistakes

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#3]
`startGameEngine` should be `startMiningGame`, I guess.
![image](https://user-images.githubusercontent.com/18144023/99881283-e14af780-2c29-11eb-8b8c-e86841c7f05b.png)
There was no `startGameEngine` function before here.

---

```javascript
term(Welcome to the mining game!)
```
Should be
```javascript
term('Welcome to the mining game!')
```

---

Double `should`.
`As a result, you should should see the message Welcome to the mining game! printed on the screen`;

**Comment by AgileNix** [comment]
fixed
