### ISSUE TITLE
task1069, have no idea how to increment aa to ab, but a to b is ok

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#30]
I've just made it to increment from a to b and so forth, but I don't understand how to work with doubled letter postfix.
Check out my code and give me a clue please.
```javascript
export const formatNumber = n => {
  const reducedNum = (n, x) => Number(n / 10 ** x).toFixed(2);

  let x;
  let postfix;
  for (let i = 1; n / 1000 ** i > 1; i++) {
    x = i * 3;
    postfix = i;
  }

  if (n >= 1e+15) return reducedNum(n, x) + String.fromCharCode(92 + postfix);
  if (n >= 1e+12) return reducedNum(n, 12) + 'T';
  if (n >= 1e+9) return reducedNum(n, 9) + 'B';
  if (n >= 1e+6) return reducedNum(n, 6) + 'M';
  if (n >= 1e+3) return reducedNum(n, 3) + 'K';
  if (n < 1000 && !Number.isInteger(n)) return Number(n).toFixed(1);
  return n + '';
};
```

```
Formatted 1234321000000000 looks like 1.23a
Formatted 12343210000000000 looks like 12.34a
Formatted 12343210000000000000 looks like 12.34b
Formatted 1.234321e+25 looks like 12.34d
```

**Comment by AgileNix** [comment]
The code is good, but it doesn't solve the task :)

The suffix should change every time the number grows by `1000`. You can try to determine how many times you need to implement the number by `1000` to stay under `999.99`.
Then, there are `26` letters in the English alphabet, which you can use to calculate the first and the letter of the suffix.

**Comment by AgileNix** [comment]
Oh, and it's a tough task. It should take you quite some time to solve.

**Comment by ssfxate** [comment]
Yeah. I've done it. Yahoo!
