### ISSUE TITLE
task #143

### ISSUE THREAD

**Issue by Kotsios-10** [AgileNix/coderslang-feedback#34]
I can't think of a way of achieving this task
Here is my take on this

```javascript
export const extractNumber = (s) => {
  let size = s.length;
  let newString;
  for(let i = 0; i<size; i++){
    if(Number(s[i]) != NaN){
      newString += s[i];
    }
  }
  return Number(newString);
}
```

It says that I failed in both:
1. extractNumber should return a number
2. extractNumber should correctly extract regular numbers

**Comment by AgileNix** [comment]
Hey, @Kotsios-10 ! That's a good one.

There are a couple of issues with your code, but first, start with fixing the `if` condition as in JavaScript `NaN` is not equal to `NaN`. Then think of how you handle the decimal points.

Also, take a look here for interesting JS tests -> https://learn.coderslang.com/tags/js-test

P. S. I've edited your issue a bit. Here's the markdown syntax guide fyi - https://www.markdownguide.org/basic-syntax/

**Comment by AgileNix** [comment]
`!isNaN(Number(s[i]))`

**Comment by Kotsios-10** [comment]
Thanks a lot for the feedback!!

**Comment by AgileNix** [comment]
@Kotsios-10 happy to help. You can close the issue if you've solved the task.

**Comment by Kotsios-10** [comment]
I'm still working on it for some reason it won't give me the beautiful green DONE

**Comment by Kotsios-10** [comment]
I have finally solved the task but it's a little complex. If you have a better way of solving this please let me know.
```
export const extractNumber = (s) => {
  let arr = [];
  let newString = ' ';
  for (let i = 0; i < s.length; i++) {
    arr.push(s[i]);
  }
  for (let i = 0; i < arr.length; i++) {
    if (!isNaN(arr[i]) || arr[i] === '.') {
      newString += arr[i];
    }
  }
  return Number(newString);
}
```

**Comment by AgileNix** [comment]
@Kotsios-10 you solved the task perfectly. The better solution will only be available after you learn regular expressions. But it's really good that you've only used what was explained in the lecture.

P. S. Please, remove the correct code to ensure other students aren't copy-pasting it blindly.

**Comment by Kotsios-10** [comment]
Okay, thanks!
