### ISSUE TITLE
Issues with importing `readline-sync`

### ISSUE THREAD

**Issue by AgileNix** [AgileNix/coderslang-feedback#35]
<img width="1045" alt="Снимок экрана 2020-12-03 в 15 50 22" src="https://user-images.githubusercontent.com/4234384/101038786-5a304480-3584-11eb-9e37-b07d425aacf6.png">

What's wrong here?

**Comment by AgileNix** [comment]
The issue is that you're trying to import the module inside of the function.

Move line 3 above line 1 and everything should be good.

**Comment by ssfxate** [comment]
Is it a real case that somebody has done?

**Comment by ycarpenter** [comment]
> The issue is that you're trying to import the module inside of the function.
> 
> Move line 3 above line 1 and everything should be good.



<img width="1044" alt="task92" src="https://user-images.githubusercontent.com/70853387/101147458-13465b80-3625-11eb-9283-766c9efba0b2.png">

Does't work

**Comment by ssfxate** [comment]
Just one step more.

You can't use dash in the name of the module that you assign in line 1, 'cause it's the mathematical expression of subtraction. Use should use camelCase syntax there.

**Comment by ycarpenter** [comment]
> Just one step more.
> 
> You can't use dash in the name of the module that you assign in line 1, 'cause it's the mathematical expression of subtraction (readline minus sync). Use should use camelCase syntax there.
> 
> The clue in the line 4.

Ok, thanks.
I hope in final version of education platform mistakes like that will take one iteration instead of two as it's now)

**Comment by AgileNix** [comment]
@ycarpenter I missed the typo in your code. @ssfxate thank you for pointing it out. Please close the issue if it's resolved.

**Comment by mohamedmehdigara** [comment]
I followed the conversation but I am still stuck. Any help?
![Capture2](https://user-images.githubusercontent.com/47916299/101277985-6f8db480-37b8-11eb-8c10-a96574faf6f5.PNG)
![Capture3](https://user-images.githubusercontent.com/47916299/101277986-70bee180-37b8-11eb-8fbc-ef40a342b042.PNG)

**Comment by ssfxate** [comment]
@mohamedmehdigara, remove the curled bracers around readlineSync.

When you are importing the whole module, you don't need them.

**Comment by mohamedmehdigara** [comment]
@ssfxate I did. Still the same error messages.

**Comment by ssfxate** [comment]
@mohamedmehdigara show your current code and the whole error from the terminal please.

**Comment by mohamedmehdigara** [comment]
@ssfxate 
![Capture3](https://user-images.githubusercontent.com/47916299/101284273-6f54df80-37df-11eb-86c6-5f6ac7c10fbb.PNG)
![Capture2](https://user-images.githubusercontent.com/47916299/101284276-70860c80-37df-11eb-8aab-158860fd52c6.PNG)

**Comment by ssfxate** [comment]
@mohamedmehdigara, have you install `readline-sync` from npm?

It should be done in the folder of the task.

**Comment by mohamedmehdigara** [comment]
@ssfxate I have installed **_readline-sync_** with **npm install readline-sync** in the task 92 folder, run the code and submit. But still the same error messages.

**Comment by ssfxate** [comment]
@mohamedmehdigara there is the same thing about importing here.

Wrong file. Read the message of the first error.

**Comment by ssfxate** [comment]
@mohamedmehdigara As I see, you've got a different error message. Could you please the whole stacktrace from you terminal?

**Comment by mohamedmehdigara** [comment]
@ssfxate Thanks For your help. I solved it. I just have to delete **import readlineSync from 'readline-sync';** from the file solutions.js and add it on top of the file helper.js
