### ISSUE TITLE
Task #92

### ISSUE THREAD

**Issue by mohamedmehdigara** [AgileNix/coderslang-feedback#37]
Hello. I am stuck here. Any help?
![Capture3](https://user-images.githubusercontent.com/47916299/101277610-f3926d00-37b5-11eb-821a-f8420ef07fec.PNG)
![Capture2](https://user-images.githubusercontent.com/47916299/101277612-f42b0380-37b5-11eb-91dc-4e173656b273.PNG)

**Comment by ssfxate** [comment]
Grab some clues here #35. I think it's about the same.

**Comment by AgileNix** [comment]
@mohamedmehdigara there are 2 ways to approach this task:
1) read this article on [how to use npm modules](https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/)
2) if #1 didn't help, skip the task for now and get back to it later

**Comment by mohamedmehdigara** [comment]
@AgileNix I solved it. Thanks for help.
