### ISSUE TITLE
task #166 - Problem with setInterval

### ISSUE THREAD

**Issue by Kotsios-10** [AgileNix/coderslang-feedback#45]
So I think I got it right.
    
    export const startCountdown = (n) => {
      let i = 0;
      setInterval(() => {
        if (i < n) {
          console.log(n - i);
          i++;
        } else {
          console.log('GO!');
          clearInterval(startCountdown);
        }
      }, 100) 
    }

But for some reason, it gives me this message.
![image](https://user-images.githubusercontent.com/75276551/101794435-8a8d5b00-3b0f-11eb-9225-e68d4ce6ebdf.png)

**Comment by ssfxate** [comment]
You're trying to clear function instead of interval.

**Comment by AgileNix** [comment]
@ssfxate is right. You should capture the interval id, which is returned by `setInterval`. Then use this id in`clearInterval`.

**Comment by AgileNix** [comment]
Btw, you can check your own console
The string `GO!` is printed quite a lot of times, but it should appear on the screen only once.

**Comment by Kotsios-10** [comment]
Thank you both for the quick feedback, have a great day!
