### ISSUE TITLE
Task 187, fields? What does it mean in object?

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#46]
**Are objects identical?**
Implement the function `isIdentical` in `helper.js`
It should take two objects and return a boolean value that tells if the **fields** of the objects are the same.
Objects will only have plain fields (strings, numbers or booleans)

What's about this task?
Should we compare keys?
Should we compare values?
Should we compare key:value pairs?
Should we compare the whole objects?

Sorry, I'm not sure, that I got the sense of the task.

**Comment by ssfxate** [comment]
What should be the result of comparing two objects like this?

```javascript
const cat = {
  name: 'Tom',
  age: '2',
  isHappy: true,
}

const dog = {
  age: '2',
  name: 'Tom',
  isHappy: true,
}
```
The code I've made which let me to pass all the checks says `false`.

**Comment by AgileNix** [comment]
@ssfxate to be identical in the context of the task means to have the same keys with the same values
