### ISSUE TITLE
Advanced Loop #187

### ISSUE THREAD

**Issue by Kotsios-10** [AgileNix/coderslang-feedback#48]
### What is your question?
- I tried so many different things to compare the 2 objects and for some reason, nothing is working!

### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What solutions have you tried to solve the task?
- I tried to compare the two objects using 
```
for(const keys1 in obj1){
    for(const keys2 in obj2){
//compare them in here
}
}
```

### Your code
```
export const isIdentical = (obj1, obj2) => {
  let arr1 = [];
  let arr2 = []
  
  for (const keys1 in obj1) {
    arr1.push(obj1[keys1]);
  }
  for (const keys2 in obj2) {
    arr2.push(obj2[keys2]);
  }
  return arr1 === arr2;
}
```

### Statuses of the checks
![image](https://user-images.githubusercontent.com/75276551/102009105-e50bfe80-3d3d-11eb-8fb9-957fc399e2e5.png)

### The output of the terminal with an error if exists
it gives me `false` which is the right answer

**Comment by AgileNix** [comment]
@Kotsios-10 try to test your function on a couple of objects. Will you ever get `true`?

You shouldn't compare the arrays, but rather the elements inside of them. Or else, just take some key from the first object and check if it's present in the second one. If it is, then check the values.

**Comment by Kotsios-10** [comment]
```
const isIdentical = (obj1, obj2) => {
  let identical;
  for(const key in obj1) {
    if(obj2.includes(key)) {
      if(obj1[key] === obj2[key]) {
        identical = true;
      } else {
        identical = false;
      }
    }
  }
  return identical;
}
```
something like this?

**Comment by ssfxate** [comment]
@Kotsios-10. what do you have as checks' results of the code?

**Comment by Kotsios-10** [comment]
Do you mean what's the output? It says that `obj2.includes(key)` is not a function

**Comment by ssfxate** [comment]
1. isIdentical should be exported from the file helper.js
2. isIdentical should be a function
3. The function isIdentical should return true if the objects are identical and false otherwise
4. The result of function isIdentical should be independent of the sequence of input parameters

**Comment by Kotsios-10** [comment]
![image](https://user-images.githubusercontent.com/75276551/102009942-79c52b00-3d43-11eb-9dee-2373a2f65371.png)

**Comment by ssfxate** [comment]
There is no .includes() for object.
Try `key` in `obj` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in

**Comment by Kotsios-10** [comment]
it gives me the right output but the submit task still says that it's false

**Comment by ssfxate** [comment]
Show to checks, please.

**Comment by Kotsios-10** [comment]
![image](https://user-images.githubusercontent.com/75276551/102010214-569b7b00-3d45-11eb-95fb-4d618d48141b.png)

**Comment by Kotsios-10** [comment]
i also modified it a little bit
```
const isIdentical = (obj1, obj2) => {
  let identical;
  for(const key in obj1) {
    if(key in obj2) {
      if(obj1[key] === obj2[key]) {
        identical = true;
      } else {
        return false;
      }
    }else{
      return false;
    }
  }
  return identical;
}
```

**Comment by ssfxate** [comment]
Try to compare this with your code. What will you get in your terminal?
``` javascript
const cat = {
  age: '2',
  name: 'Tom',
  isHappy: true,
}

const dog = {
  name: 'Tom',
  age: '2',
  isHappy: true,
}
```

**Comment by Kotsios-10** [comment]
it gives me true

**Comment by ssfxate** [comment]
What's about those? It should give you false.
const cat = {
  age: '2',
  name: 'Tom',
  isHappy: true,
}

const dog = {
  name: 'Tom',
  age: '2',
  isHappy: true,
  trick : '2'
}

**Comment by Kotsios-10** [comment]
damn it gives me true

**Comment by AgileNix** [comment]
@Kotsios-10 what if there's a field in `obj2` that's missing in `obj1`?

I see that the last example from @ssfxate pointed out this issue.

**Comment by Kotsios-10** [comment]
I tried fixing it but I got nothing

**Comment by AgileNix** [comment]
Skip it for now, and come back to this task later. It's ok.
