### ISSUE TITLE
TASK 2031, there is a bug in checks

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#50]
### How have you realized this?
I made my changes and sent the code to the server.
The result looks as the task description prescribed it.

### What solutions have you tried to solve the task?
Changed the tag from `<strong></strong>` to `<b></b>`.
It passed, but all checks haven't describe the real problem with `<strong></strong>`.

### Your code
```html
<strong>In 3 months I will become a high skilled Full Stack developer!</strong>
```

### Statuses of the checks
FAILED 1. You should add a single tag into index.html
FAILED 2. All the content in inner.html should be placed inside the tag

### The output of the terminal with an error if exists
Nothing

**Comment by AgileNix** [comment]
We've improved the task description. Thank you for pointing out the issue.
