### ISSUE TITLE
LECTURE 204, typos and broken styles

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#52]
https://js.coderslang.com/lecture/204

### Forgotten spaces after equal
```
<p align ="center"> - attribute align with value center - will add center alignment to the text inside the paragraph
<hr color ="red"> - attribute color with value red - will change the color of the horizontal rule to red
<p align ="right"> - attribute align with value right - will add right-alignment to the text inside the paragraph
```

### Broken styles
![image](https://user-images.githubusercontent.com/18144023/102400867-88396e00-3ff3-11eb-8fb8-8d2d34629c8c.png)

**Comment by AgileNix** [comment]
Fixed. Thank you.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/4234384/102407977-9ee0c480-3ff5-11eb-9c28-46501688cb6f.png">
