### ISSUE TITLE
Novice Exam 250 stage 10

### ISSUE THREAD

**Issue by Kotsios-10** [AgileNix/coderslang-feedback#55]
### What is you question?
I think it gives me the wrong message, but I'm not sure.
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What soultions have you tried to solve the task?
```
import {updateGold} from './functions.js';
export const handleKeyPress = (term, state) => {
    return (name, matches, data) =>{
        const key = String.fromCharCode(data.code);
        if (key === "G" || key === "g"){
            state.gold++;
        }
        
        for (const obj of state.producers) {
            if (obj.id == key && state.gold >= obj.cost){
                state.gold -= obj.cost;
                obj.cost *= obj.growthRate;
                obj.count++;
                state.productionRate++;
            }
        }
    }
}

export const handleStateChange = (term, state) =>{
    return () =>{
        updateGold(term,state);
    }
}
```
This is the whole code for handlers.js but what the program says I did wrong is the `state.productionRate++;` in the `for(const obj of state.producers)`

### Statuses of the checks
![image](https://user-images.githubusercontent.com/75276551/102621082-c051c580-4147-11eb-86c8-72d46c61c577.png)

**Comment by AgileNix** [comment]
@Kotsios-10 with `state.productionRate++` you're incrementing total production by 1 regardless of which producer was purchased. This is incorrect as different producers have different productivity.

**Comment by Kotsios-10** [comment]
okay thanks i fixed it
