### ISSUE TITLE
250 Stage 13

### ISSUE THREAD

**Issue by Kotsios-10** [AgileNix/coderslang-feedback#56]
### What is you question?
I'm printing the message in the right format but it says that's not.
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [x] Yes

### What soultions have you tried to solve the task?
```
export const updateProducerList = (term, state) => {
    term.moveTo(1, 5);
    for (const obj of state.producers) {
        if (obj.count >= 0) {
            term(`${obj.title}: ${obj.count} | Production per second: ${obj.baseProduction} | Cost: ${obj.cost}`);
        }
    }
    state.isProducerListUpdated = true;
}
```
This is my code and the format should look like this: **_Miner: 2 | Production per second: 0.1 | Cost: 12.8_**
### Statuses of the checks
![image](https://user-images.githubusercontent.com/75276551/102709399-fcee0000-42b2-11eb-976e-7e0880c1d152.png)

**Comment by AgileNix** [comment]
@Kotsios-10 the format is a bit off. You forgot to add the rounding. Use `.toFixed(1)` for `baseProduction`.

Everything else looks good.

**Comment by AgileNix** [comment]
@Kotsios-10 have you resolved the issue?

**Comment by Kotsios-10** [comment]
I havent continued the course for like a month. School started and its hard to keep up. I'll close the issue
