### ISSUE TITLE
task 104 (code may confuse people)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#59]
![image](https://user-images.githubusercontent.com/18144023/104507005-34707380-55f7-11eb-9565-bf3ad3d72cd1.png)
This code has been passed, but from this solution, students couldn't learn what they should learn.
I think the functions should be renamed to avoid confusing the students.

**Comment by AgileNix** [comment]
@ssfxate the naming of the functions was chosen on purpose to make sure the student understands the difference between `toLowerCase(s)` and `s.toLowerCase()`. It might be too early for such a task, though.

**Comment by ssfxate** [comment]
I got you. Unfortunately, it works oppositely sometimes.
