### ISSUE TITLE
If the user presses a key that corresponds to the manufacturer id, we must

### ISSUE THREAD

**Issue by w0rstR** [AgileNix/coderslang-feedback#6]
TASK 250 stage 9
How to implement If logic
Something like this happened to me
if(String.fromCharCode(data.code)== config.producers.keys('id'))

**Comment by AgileNix** [comment]
what is `config.producers.keys('id')`?
`producers` is an array. You should find the element in this array.

**Comment by w0rstR** [comment]
![gggh](https://user-images.githubusercontent.com/64990075/99900838-e1470800-2cba-11eb-9b8b-b86760758b7a.JPG)
Did you properly implement the producers array?
I can't implement this logic
Tell me please
If the user presses a key that matches the manufacturer id
check on keys of an array?

**Comment by AgileNix** [comment]
You should check each element of the array to find the one that has the correct id inside of it. Use a loop.

**Comment by w0rstR** [comment]
```
Status: FAILED.

PASSED 1. handleKeyPress shouldn't have any effect on the state if the user has pressed the irrelevant button
FAILED 2. gold should be decreased by the cost of the producer after the purchase is completed
FAILED 3. the price of the next producer should become equal to 'cost * growthRate' after a purchase
FAILED 4. the count of producers of the appropriate type should increase after the purchase

import {updateGold} from './functions.js'
import {config} from './constants.js'
export const handleKeyPress=(term, state)=>{
   return function poingG(name,matches,data){
        if(String.fromCharCode(data.code)== 'G'|| String.fromCharCode(data.code)=='g'){
            
         state.gold++
        //    return updateGold(term,state)
        return updateGold(term, state);
       }

       let element;
       producers.foreach(item => {
           if (item.id == String.fromCharCode(data.code)){
           element = item;
           
           state.gold-=element.cost
           element.cost*=element.growthRate
           element.count++
           }
       })
       
      
   }
}
```

**Comment by ssfxate** [comment]
At least I see a mistake in foreach. It should be camelCase.

**Comment by AgileNix** [comment]
@w0rstR Try running your code before submitting it. If it fails, then it for sure won't pass the checks.

Also, I suggest only using the material that was covered in lectures. A regular `for` loop works perfectly here. You don't need `forEach`, which you've misspelled, btw.

**Comment by AgileNix** [comment]
@w0rstR have you managed to solve the task?
