### ISSUE TITLE
Task 250

### ISSUE THREAD

**Issue by Drabo-2010** [AgileNix/coderslang-feedback#60]
I've made my own solution for the 9th step of this test. See screenshots to understand. It does not complete. To control the flow of the process added some test outputs to the programm. And everything work in tests but fail in submit task! Help!
![Снимок экрана_2021-01-15_14-47-39](https://user-images.githubusercontent.com/70754473/104731226-16fcf000-5744-11eb-99b9-8dd567090c28.png)
![Снимок экрана_2021-01-15_14-55-54](https://user-images.githubusercontent.com/70754473/104731231-17958680-5744-11eb-8e87-56f4c5e97f72.png)

**Comment by AgileNix** [comment]
@Drabo-2010 you should use the `data.code` instead of the `name` to analyze the key pressed.

Also, it's helpful if you provide your source code as text using the markdown syntax. This way we can copy and paste it to ensure it works. [markdown guide](https://www.markdownguide.org/)

**Comment by Drabo-2010** [comment]
Ok. As i understand, in further tasks it will be important to use the hard way (data.code) instead of simple to use and understand (name)?

**Comment by Drabo-2010** [comment]
It's not a problem to change this, but I thought programmers try to make simple code.

**Comment by ssfxate** [comment]
Yes, you're right, but simultaneously they can do some practices accordingly to their experience and code something before it will appear. They are preparing a basement to avoid big reconstruction when the next step comes.

Concluding: It depends on a certain experience of a certain developer.

**Comment by AgileNix** [comment]
@Drabo-2010 the `name` param is missing on some systems, so we can't use it to reliably check the key pressed. Please close the issue if it's resolved.

**Comment by Drabo-2010** [comment]
Thanks a lot
