### ISSUE TITLE
List of tasks for the lecture 209

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#63]
Look at the name of the first task. It should be in English, 'cause my interface language is English.
![image](https://user-images.githubusercontent.com/18144023/105062288-7d0ead80-5a8b-11eb-87b5-c3778bbb183b.png)
By contrast in Russian, it has the name in English.
![image](https://user-images.githubusercontent.com/18144023/105062492-b47d5a00-5a8b-11eb-8b5f-414437f1515a.png)

**Comment by ssfxate** [comment]
An extra period after the second task's name.

**Comment by AgileNix** [comment]
Fixed, thank you.
