### ISSUE TITLE
Bug in a link of external css (TASKS 210*)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#65]
### What solutions have you tried to solve the task?
I've used the same way as I read in the [lecture 210](https://js.coderslang.com/lecture/210).
```css
h1 {
  text-align: center;
}
```

### Your code
![image](https://user-images.githubusercontent.com/18144023/106380038-ced70200-63c0-11eb-8264-fa4dae96afbe.png)
![image](https://user-images.githubusercontent.com/18144023/106380062-ef06c100-63c0-11eb-808b-8b45cd4412e6.png)

### Statuses of the checks
```
PASSED 1. There should be one styles.css file.
PASSED 2. There should be only one <link> tag in the document
PASSED 3. The href attribute of the <link> tag should be ./styles.css
PASSED 4. There should be only one <h1> heading in the document
FAILED 5. Text in the <h1> heading should be aligned to the center
```

**Comment by ssfxate** [comment]
Similar thing in 2102
![image](https://user-images.githubusercontent.com/18144023/106380158-705e5380-63c1-11eb-9970-922f64520caf.png)

**Comment by ssfxate** [comment]
2103
![image](https://user-images.githubusercontent.com/18144023/106380379-e2836800-63c2-11eb-95ff-42a1090ad69d.png)

**Comment by ssfxate** [comment]
2104
![Uploading image.png…]()

**Comment by ssfxate** [comment]
2105 as well

**Comment by AgileNix** [comment]
@ssfxate fixed. Thank you for the bugreport.
