### ISSUE TITLE
task92, how to import `readline-sync`

### ISSUE THREAD

**Issue by esenbaevbeknazar** [AgileNix/coderslang-feedback#75]
#### task92/helper.js
  ```js
  export const askNameAndGreet = () => {
  const name = readlineSync.question('Please enter your name: ');
  
  console.log(`Hello, ${name}!`);
}

  ```
        
  #### task92/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task92/solution.js
  ```js
  /**
 * The code is broken.
 *
 * You need to install the module readline sync and import it
 *
 * Only one import string should be added to helper.js.
 *
 * Don't change solution.js.
 * */

import { askNameAndGreet } from './helper.js'

askNameAndGreet();
  ```

**Comment by ssfxate** [comment]
What is your question?

**Comment by AgileNix** [comment]
@esenbaevbeknazar you should install and import the module `readline-sync`.

Follow these links for more information:
https://learn.coderslang.com/0014-how-to-import-and-use-npm-modules/
https://learn.coderslang.com/0011-how-to-use-open-source-npm-packages/

**Comment by alex1der-dev** [comment]
i installed read-sync using `npm install read-sync`, but no succes

**Comment by AgileNix** [comment]
@esenbaevbeknazar I'm closing this issue as inactive. Feel free to reopen it if you still need help.
