### ISSUE TITLE
Suggestion for the task 1

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#76]
If I `Run my code` and have an old version of Node JS I can have the task done, but still have not finally set up the environment.

For example. I have Node 10.23.1 by default in NVM and the task has passed.

### What is your suggestion?

Add a code to use a modern version of the Node JS.

**Comment by AgileNix** [comment]
@ssfxate makes sense, I'll keep it open until we find a viable solution

**Comment by AgileNix** [comment]
@ssfxate we've added a warning that is displayed right above the "RUN" button if the user has an outdated version of Node.js. At the moment it's the best we can do, as we don't want to do any "hacking" into the users' machine and install or update node.js for them.
