### ISSUE TITLE
 internalBinding('errors').triggerUncaughtException

### ISSUE THREAD

**Issue by w0rstR** [AgileNix/coderslang-feedback#8]
![222222222](https://user-images.githubusercontent.com/64990075/99885824-46114c80-2c40-11eb-807b-779557cb72aa.JPG)
TASK 152

**Comment by ssfxate** [comment]
Try to add `.js` extension to the place where you import `./helper'.
It'll look like `./helper.js`

**Comment by AgileNix** [comment]
@w0rstR most likely this is the case with `.js`. We've fixed the initial task files.
