### ISSUE TITLE
[TASK] [92]

### ISSUE THREAD

**Issue by Gandalf1605** [AgileNix/coderslang-feedback#81]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [] Yes

### What solutions have you tried to solve the task?
import {readlineSync} from '../node_modules/readline-sync/lib/readline-sync.js';
### Your code

content of file "helper.js"

import {readlineSync} from '../node_modules/readline-sync/lib/readline-sync.js';

export const askNameAndGreet = () => {
  const name = readlineSync.question('Please enter your name: ');

  console.log(`Hello, ${name}!`);
}

### Statuses of the checks
1. Ты должен импортировать функцию readlineSync в 'helper.js' из модуля 'readline-sync'.

2. Функция askNameAndGreet должна запрашивать имя с помощью функции readlineSync.question()

3. Функция askNameAndGreet должна выводить в консоль одно сообщение

4. Функция askNameAndGreet включает имя пользователя в приветствие
### The output of the terminal with an error if exists
PS D:\CODERSLANG\task92> node d:/CODERSLANG/task92/solution.js
internal/modules/cjs/loader.js:1172
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: d:\CODERSLANG\task92\solution.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by ssfxate** [comment]
When you use `{readlineSync}` you're trying to import a function named `readlineSync` from the module.

Remove curled bracer to import the whole module.

**Comment by AgileNix** [comment]
@Gandalf1605 you shouldn't specify the whole path to the module. Just the `readline-sync` part.

```js
import readlineSync from 'readline-sync';
```

**Comment by ssfxate** [comment]
Check for closed Issues for some clues
https://github.com/AgileNix/coderslang-feedback/issues?q=task+92

**Comment by AgileNix** [comment]
@Gandalf1605 I'm closing this one as resolved. Feel free to reopen the task if you still have issues.
