### ISSUE TITLE
LECTURE 214 (typos)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#84]
In the Russian version some wrong tabulations and other layout things.
![image](https://user-images.githubusercontent.com/18144023/108601934-52788300-73b0-11eb-8db9-cd14dba93ac3.png)
![image](https://user-images.githubusercontent.com/18144023/108601936-599f9100-73b0-11eb-9173-462e84e31f86.png)
![image](https://user-images.githubusercontent.com/18144023/108601939-5f957200-73b0-11eb-906f-de530e159fa5.png)

**Comment by ssfxate** [comment]
No backticks around params in the description of the English and Russian versions
![image](https://user-images.githubusercontent.com/18144023/108602014-cdda3480-73b0-11eb-8305-9cf3d8666e38.png)
![image](https://user-images.githubusercontent.com/18144023/108602022-d9c5f680-73b0-11eb-9a38-4c6cebe342c1.png)

**Comment by amatiyko** [comment]
@ssfxate done.
Please, delete task2141 folder and then download tasks again to see changes.
