### ISSUE TITLE
task 85

### ISSUE THREAD

**Issue by Evgeniy1970-ai** [AgileNix/coderslang-feedback#85]
### Have you tried to find an answer in [other issues](https://github.com/AgileNix/coderslang-feedback/issues?q=is%3Aissue)? 
- [ ] Yes

**Comment by Evgeniy1970-ai** [comment]
## Task: 85

## User implementation 

  #### task85/solution.js
  ```js
  /**
 * This task might contain some unfamiliar things.
 *
 * Don't be scared.
 *
 * You need to fix one character to make sure that myMessage is printed out to the console in uppercase letters.
 * */



 function printUpperCaseMessage (message) {
  console.log(message.toUpperCase());
}

myMessage = `I'm on a path to becoming a JS developer!`;

printUpperCaseMessage(myMessage);

  ```

**Comment by AgileNix** [comment]
@Evgeniy1970-ai `myMessage` is not defined. Check the lecture and make it either a variable with `let` or a constant with `const`

**Comment by Evgeniy1970-ai** [comment]
Thanks, I've done
