### ISSUE TITLE
[TASK] [NUMBER]

### ISSUE THREAD

**Issue by esenbaevbeknazar** [AgileNix/coderslang-feedback#86]
## Test result 

  - [x] {
  "en": "`sum` should be exported from the file 'helper.js'",
  "ru": "`sum` нужно экспортировать из файла 'helper.js'"
}
        
  - [x] {
  "en": "`sum` should be a function",
  "ru": "`sum` должна быть функцией"
}
        
  - [ ] {
  "en": "Function `sum` should take two numbers and return their sum",
  "ru": "Функция `sum` должна принимать два числа и возвращать их сумму"
}
        
#### task101/helper.js
  ```js
  
export const sum = (sum) => {
    return 4 + -6;
}
  ```
        
  #### task101/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task101/solution.js
  ```js
  /**
 * Implement a function sum in helper.js which should return the sum of two numbers
 * */

import { sum } from './helper.js';

console.log(sum(2, + 2));   // 4
console.log(sum(-1, + -5)); // -6
  ```

**Comment by ssfxate** [comment]
You're not defining any variables in your `sum` function. Thus no actions with different numbers. You're just returning the fixed expression `4 + -6`.

Re-read the lecture again. There is the exact example https://js.coderslang.com/lecture/10

**Comment by AgileNix** [comment]
@esenbaevbeknazar start with this
```js
export const sum = (x, y) => {
  // return the sum of the numbers `x` and `y` in the next line
}
```
