### ISSUE TITLE
[TASK] [NUMBER]

### ISSUE THREAD

**Issue by GregoryDmitriev** [AgileNix/coderslang-feedback#88]
#### task85/solution.js
  ```js
  /**
 * This task might contain some unfamiliar things.
 *
 * Don't be scared.
 *
 * You need to fix one character to make sure that myMessage is printed out to the console in uppercase letters.
 * */

function printUppercaseMessage (myMessage) {
  console.log(myMessage.toUpperCase());
}

get ('myMessage') = `I'm on a path to becoming a JS developer!`;

printUppercaseMessage(myMessage);

  ```

**Comment by luizvicentin** [comment]
@GregoryDmitriev Do you still need some help?

**Comment by ssfxate** [comment]
Re-read the lecture 8 https://js.coderslang.com/lecture/8
Try to find something that looks like `get` but has one letter different.

**Comment by AgileNix** [comment]
@GregoryDmitriev you've made too many changes. There's no need to wrap `myMessage` in quotes and braces. Just define it as a regular variable using `let`.

If you want to reset the task to the initial state - delete the task folder and download the tasks again.
