### ISSUE TITLE
task166, wrong requirements

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#9]
The description says
```The delay between calls to the console.log should be 1 second.```

But if I do this in
```javascript
export const startCountdown = (n) => {
  let i = 0;
  const timer = setInterval(() => {
    if (i < n) {
      console.log(n - i);
      i++;
    } else {
      console.log('GO!');
      clearInterval(timer);
    }
  }, 100) // here I tried to set 1000
}
```
It gives me failed first assertion.
`1. startCountdown should start the interval that runs every 100 ms`

P.S. It passed with `100 ms`…

**Comment by AgileNix** [comment]
@ssfxate the issue was only present in solution.js. Fixed.
