### ISSUE TITLE
[TASK] [NUMBER]121

### ISSUE THREAD

**Issue by enginokurs** [AgileNix/coderslang-feedback#91]
## Test result 

  - [x] {
  "en": "`min` should be exported from the 'helper.js' file",
  "ru": "`min` нужно экспортировать из файла 'helper.js'"
}
        
  - [x] {
  "en": "`min` should be a function", 
  "ru": "`min` должна быть функцией"
}
        
  - [ ] {
  "en": "The `min` function should return the minimum of 3 numbers",
  "ru": "Функция `min` должна возвращать минимальное из 3 чисел"
}
        
  - [ ] {
  "en": "`min` should not return undefined",
  "ru": "`min` не должна возвращать undefined"
}
        
#### task121/helper.js
  ```js
export const min = (a=0, b=0, c=0)=>{
  if ((a<b && a<c) !=='undefined') {
    return a;
  } else if((b<a && b<c) !=='undefined') {
    return b;
  }else if ((c<b && c<a) !=='undefined') {
    return c;
  }
  }
  ```
        
  #### task121/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task121/solution.js
  ```js
  /**
 * Implement a function min that takes three numbers and returns the smallest one
 * */

import { min } from './helper.js';

const a = 5;
const b = 7;
const c = undefined;

console.log(`The minimum is ${min(a, b, c)}`);
  ```
        

please can you show me the solution? i almost tried everything but still get error.

**Comment by AgileNix** [comment]
@enginokurs I see a couple of issues here
1) the comparison with undefined in excessive. Let's start with regular numbers.
2) the default values are unnecessary too.
3) what does your function return if all the arguments are equal? (this is the most important one)

**Comment by enginokurs** [comment]
1.i have to set a const as "undefined" so we can see the output. thats why i changed. and works, returns "0".
2. if so, how do we know whether the function to output "undefined" or not? 
3. if i set up for example 5 to all consts, it returns minimum is 5.so what is it supposed to say?
4. what do you mean "regular numbers".
can you show me solution?

**Comment by enginokurs** [comment]
i'm waiting for solution. i couldn't make any progress in the program for 2 days for this thing. if i dont get any answer, i will have to delete your app from vscode.

**Comment by amatiyko** [comment]
@enginokurs 
> what does your function return if all the arguments are equal? (this is the most important one)

It should just return this number. You don't need this check `c<b && c<a` just `return c;` instead.

**Comment by enginokurs** [comment]
i tried last time and surprisingly, it worked.
