### ISSUE TITLE
LECTURE 216 (typos)

### ISSUE THREAD

**Issue by ssfxate** [AgileNix/coderslang-feedback#92]
![image](https://user-images.githubusercontent.com/18144023/109432387-f222ba80-7a1b-11eb-975b-174ed4219b57.png)
![image](https://user-images.githubusercontent.com/18144023/109432394-f7800500-7a1b-11eb-8b11-7f80579f340c.png)

**Comment by ssfxate** [comment]
![image](https://user-images.githubusercontent.com/18144023/109432406-0d8dc580-7a1c-11eb-9d66-0871e2ef7c9e.png)

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for the report.

**Comment by amatiyko** [comment]
@ssfxate fixed. Thank you for the report.
