### ISSUE TITLE
Task 250, Step/subtask 6

### ISSUE THREAD

**Issue by AgileNix** [AgileNix/coderslang-feedback#93]
Thanks for the help!

Can you help with step 6

## Test result 

  - [x] {
  "en": "`startMiningGame` should call `term.on()` with the `key` as a first param and a handler function as a second one",
  "ru": "`startMiningGame` должна вызывать `term.on()` с `key` в качестве первого параметра и функцией обработчика в качестве второго."
}
        
  - [x] {
  "en": "`startMiningGame(term, state)` should call `handleKeyPress(term, state)`",
  "ru": "`startMiningGame(term, state)` должна вызывать `handleKeyPress(term, state)`"
}
        
  - [x] {
  "en": "`init(term)` should call `term.clear()` once",
  "ru": "`init (term)` должна вызывать `term.clear ()` один раз"
}
        
  - [x] {
  "en": "`init(term)` should call `term.hideCursor()` once",
  "ru": "`init (term)` должна вызвать `term.hideCursor()` один раз"
}
        
  - [x] {
  "en": "`init(term)` should call `term.grabInput()` once",
  "ru": "`init(term)` должна вызывать `term.grabInput()` один раз"
}
        
  - [ ] {
  "en": "The callback function passed into `term.on` should increment the `state.gold` when the G key is clicked",
  "ru": "Функция обратного вызова, переданная в `term.on`, должна увеличивать значение `state.gold` при нажатии клавиши G"
}
        
#### task250/constants.js
  ```js
  import terminalKit from 'terminal-kit';
export const term = terminalKit.terminal;
export const config = {
    gold: 0,
}
  ```
        
  #### task250/functions.js
  ```js
  export const init = (term) => {
    term('Welcome to the mining game!');
    term.clear();
    term.hideCursor();
    term.grabInput();
};

  ```
        
  #### task250/gameEngine.js
  ```js
  import {init} from './functions.js';
import { handleKeyPress } from './handlers.js';
export const startMiningGame = (term, config) =>{
    init(term);
    term.on('key', handleKeyPress);
    handleKeyPress(term, config);
};

  ```
        
  #### task250/handlers.js
  ```js
  

export const handleKeyPress = (term, state) =>{
    return (name, matches, data) => {
        if (String.fromCharCode(data.code) === 'G' || String.fromCharCode(data.code) === 'g')
            {state.gold++;}
    }
};
  ```
        
  #### task250/package.json
  ```json
  {
  "name": "solution",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "solution.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}

  ```
        
  #### task250/solution.js
  ```js
  // LET'S DIG SOME GOLD!
import {term} from './constants.js';
import {config} from './constants.js';
import {startMiningGame} from './gameEngine.js';
console.log(startMiningGame(term, config));

  ```

_Originally posted by @PashaKycher in https://github.com/AgileNix/coderslang-feedback/issues/90#issuecomment-788995685_

**Comment by AgileNix** [comment]
I'm unable to run your code at the moment, but it looks like the issues is here:
```js
term.on('key', handleKeyPress);
```

Look at the signature of `handleKeyPress`, shouldn't you pass 2 params into it?

**Comment by PashaKycher** [comment]
thanks for the help

**Comment by AgileNix** [comment]
@PashaKycher once the issue is resolved, please close it. This way we'll know that you don't need any extra help with this task.
