### ISSUE TITLE
[TASK] [103]

### ISSUE THREAD

**Issue by VladiKinz** [AgileNix/coderslang-feedback#94]
Help me with Task, i cant understand what me do...

const PI = 3.14159265359;

export const circleLength = (radius) => {
  return PI * 4 / radius;
}

import { circleLength } from './helper.js';

console.log(circleLength(5));
console.log(circleLength(12));

**Implement a function circleLength that calculates and returns the length of the circle given its radius!!!**

**Comment by ssfxate** [comment]
Hey. What's the formula for the length of a circle?

**Comment by AgileNix** [comment]
@VladiKinz you've made one small mistake. The formula that you've used it incorrect.
This will fix it:
```javascript
return PI * 2 * radius;
```

**Comment by AgileNix** [comment]
@VladiKinz closing this one as resolved
