### ISSUE TITLE
I have crooked hands

### ISSUE THREAD

**Issue by PashaKycher** [AgileNix/coderslang-feedback#95]
On task 250 stage 8, I need to export the "producers" array from "solution.js" to "constants.js" "config".

solution.js

import {producers} from './solution.js';
import terminalKit from 'terminal-kit';

export const term = terminalKit.terminal;
export const config = 
    {
        gold: 0,
        producers: producers,
    };

solution.js

export const producers = 
    [
        { id: 1, title: 'Miner', cost: 10, growthRate: 1.13, baseProduction: 0.1, count: 0 },
        { id: 2, title: 'Adventurer', cost: 100, growthRate: 1.17, baseProduction: 1, count: 0 },
        { id: 3, title: 'Professional', cost: 1200, growthRate: 1.14, baseProduction: 9, count: 0 },
    ];

import {term} from './constants.js';
import {config} from './constants.js';
import {startMiningGame} from './gameEngine.js';
console.log(startMiningGame(term, config));

When my code looked like this, it would throw an error when checking, "term is not a function". And in the theremin it displays this:

Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Попробуйте новую кроссплатформенную оболочку PowerShell (https://aka.ms/pscore6)

PS D:\Programs\Work Dir> node d:/Programs/"Work Dir"/task250/solution.js
file:///d:/Programs/Work%20Dir/task250/constants.js:8
        producers: producers,
                   ^

ReferenceError: Cannot access 'producers' before initialization
    at file:///d:/Programs/Work%20Dir/task250/constants.js:8:20
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
PS D:\Programs\Work Dir> 

For experimentation, I rewrote the code like this:

//import {producers} from './solution.js';
import terminalKit from 'terminal-kit';

export const term = terminalKit.terminal;
export const config = 
    {
        gold: 0,
        producers:     [
            { id: 1, title: 'Miner', cost: 10, growthRate: 1.13, baseProduction: 0.1, count: 0 },
            { id: 2, title: 'Adventurer', cost: 100, growthRate: 1.17, baseProduction: 1, count: 0 },
            { id: 3, title: 'Professional', cost: 1200, growthRate: 1.14, baseProduction: 9, count: 0 },
        ],
    };

the task was successfully verified.

Now I can’t double-check this stage and I can’t figure out what I was wrong initially. What to do?

**Comment by ssfxate** [comment]
Hey, Pasha. May I suggest to you to learn the topic about markdown?
https://guides.github.com/features/mastering-markdown/
